### ISSUE TITLE
Bug when playing the Insulation card

### ISSUE THREAD

**Issue by Shadragul** [bafolts/terraforming-mars#1]
When playing the Insulation card, when I select an amount of heat production to lose and hit "Save" absolutely nothing happens.  I have tried selecting different values to decrease heat production, but none of the available choices works.

Card data:
Insulation Costs 2. Decrease your heat production any number of steps and increase your mega credit production the same number of steps Better insulation means lower energy spending

 I figure it would be easier for you to see the state of the game upon playing and paying for Insulation:
https://terraforming-mars.herokuapp.com/game?id=a7c09da40aeb
https://terraforming-mars.herokuapp.com/player?id=9e0c7cd228ec

**Comment by bafolts** [comment]
I need to add better support for displaying what the server thinks the error was to the user. When you clicked "Save" (yes the current UI needs a lot of improvements) the server most likely had some error it could have shown you which would have been helpful in this situation. With the heroku services setup right now the games are not persisted. Since that is the case the provided links are no longer valid. Thanks for this bug report. I should be able to recreate this within the unit tests and see more information in the heroku logs.

**Comment by bafolts** [comment]
This is fixed in `master`. The fix went in with this commit https://github.com/bafolts/terraforming-mars/commit/eebc97f3f8b12cc599bbd258ae365f27e14c3d29#diff-b4f7251bcf3158865150fe06e3e6458cR13. In the `SelectAmount` component the `onsave` was never being called so nothing useful would happen upon clicking `Save`.

**Comment by bafolts** [comment]
This fix has been deployed to the heroku app.
