### ISSUE TITLE
Randomize Origrinal Board; Feature Description and Implement

### ISSUE THREAD

**Issue by Ronnoc** [bafolts/terraforming-mars#1014]
Hi,
I have made the Original Board shuffable and restorable

code in https://github.com/Ronnoc/terraforming-mars/commit/859ea881f19154e2c3fcc4e6d24a32e96b4df1fc

I can make a pull request if needed

sample output image like (the noctis city may in water)

![shuffledboard](https://user-images.githubusercontent.com/5140023/87850789-80cb4700-c925-11ea-9c86-259c8bc4a72c.png)

**Comment by nwai90** [comment]
It's interesting, I like the idea. Having an option for a dynamic board would make every game quite different.

Noticed that the commit contains some other changes though (e.g. fan-made awards, localization). Could you raise a PR with isolated changes for this specific feature?

We may also want to find a way to deal with the labels for Noctis City and volcanic areas, since those areas will also (presumably) be shuffled if the board is randomised.

**Comment by ssimeonoff** [comment]
Removes the labels from the "mars.png" and adding them to the respective "data_space_id" should be easy.
E.g. "Noctis" and "Volcano" for all the rest.

**Comment by nwai90** [comment]
Implemented by @Ronnoc in https://github.com/bafolts/terraforming-mars/pull/1015
