### ISSUE TITLE
Random board option now unclear

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1052]
Here's what the option looks like at game setup
![image](https://user-images.githubusercontent.com/4755233/88330450-4294a580-cce0-11ea-8b7d-31fb6da58c1d.png)

Before there was the "radomized orange board locations" this button meant that a player wanted to have one of the 3 base maps, but didn't want to decide on their own (very similar to "random start player"). This button now means something different. There's no problem with that, but it takes away from the old functionality. To me, the new meaning is like you switched the meaning of "random start player" to "move the letters of a start player's name to be in random positions". It's certainly a new feature, but I'd also like the old feature.

As such, I'd like to rename the current "Random" to "Mixed up", and have the old random option come back.

Furthermore, it would be nice to have the option of randomizing between the maps of my choice, so if I wanted the mixed up board, or hellas as options, I could randomize just between those.

**Comment by nwai90** [comment]
@duckmammal Can you clarify what the issue is?

I tried it out - if "Random" is selected, it will give one of the three boards chosen at random. This behaviour is the same as before.

If "Random" is selected together with "Randomize board tiles", a random map will be chosen and the tiles will be shuffled. This is also consistent with what the options mean.

**Comment by duckmammal** [comment]
ack you're right! I didnt realize that "randomize board tiles" was an option, and i was just turning on all the options, which is how i was setting up a game!
