### ISSUE TITLE
Feature request: after game end, option to submit statistics to Simeon's database

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1118]
After the game end, present an option to submit the game result to Simeon's database (https://ssimeonoff.github.io/stats). @ssimeonoff

**Comment by nwai90** [comment]
This is a nice idea! I can see it potentially being combined with social sharing as well (e.g. share game result to FB/Twitter/Telegram/Whatsapp)

**Comment by ssimeonoff** [comment]
Firebase is running out of juice, so it is better push to a new proper db. 

It is really badly built - I download the whole db in the client and then do all calculations there.  My excuse is that when I built it I barely knew any frontend and had no idea about backend or databases. 

Stats are fun, but if you do it now - do it properly, instead of pushing data to my dying Firebase.

**Comment by vincentneko** [comment]
We could use the same database used by the app.
The problem right now is that we do not authenticate users, so any one can use any name.
We could start this way and update once we have a proper authentication method.

I will submit a PR with a new database table along with a query to populate game results.

**Comment by vsrisuknimit** [comment]
I would not care too much about personal stats. So player names should not matter much.

I am more interested in looking at corps win rate, points, number of generations played, number of players, etc.

**Comment by chosta** [comment]
We are thinking about an app that is running on a separate server to hold any kind of statisical data.
It would be an API that would allow writing and reading (and storing) of game scores. Will keep you updated on this one.

**Comment by vincentneko** [comment]
I've also added a new table to the database to store game results.

**Comment by vsrisuknimit** [comment]
closing for now
