### ISSUE TITLE
Bug: aquifer pumping payment

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1185]
Currently aquifer pumping as first where you want to put the ocean, place the ocean, give the player the rebate, and then ask to pay.

I believe the payment part of the action (left of red arrow) must come first. In this case, you cannot use the ocean rebate bonus to pay for the cost of playing the ocean itself down.

**Comment by nwai90** [comment]
@vsrisuknimit Is this similar to the issue raised in https://github.com/bafolts/terraforming-mars/issues/1178?

For Aquifer Pumping action, we currently check if the player can afford to pay 8 MC using MC and steel. If the player cannot afford this cost, the action will not be available.

There is a minor exploit possible here in that the player might be able to afford using both steel and MC (e.g. player has 4 MC and 2 steel before placing the ocean), but chooses to pay using 8 MC after gaining 4 MC ocean placement bonus.

You're right that it is technically a glitch, since the player should be forced to spend 2 steel to pay for the action cost before receiving placement bonuses. There are some cases where keeping this steel could provide a benefit (e.g. Industrialist and Miner awards).

**Comment by vsrisuknimit** [comment]
@nwai90 I think it might be related to #1178. 

Any reason we don't ask the player to pay first before ocean placement? Does that interfere with anything?

**Comment by vincentneko** [comment]
> @nwai90 I think it might be related to #1178.
> 
> Any reason we don't ask the player to pay first before ocean placement? Does that interfere with anything?

This is due to interrupt mechanism. We can switch the order (pay first then place ocean), will submit a PR for this.
Same for Water Import From Europa.

If you think about other cases please let me know.

**Comment by vincentneko** [comment]
This one is not related to #1178 
#1178 occurs when interrupt events and non-interrupts events are triggered at the same time.

**Comment by vincentneko** [comment]
Fixed
