### ISSUE TITLE
Black list for some cards on game creation form

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#1197]
What about possibility to ban some cards from the game?

I see it like suggest input box. When user starts to type the text into that input box application is showing max 10 cards matching input by name. If user clicks some of the suggestions it is displayed under that input box (can be removed then). After click by "Create Game" application creates new game as usual but cards from black list are removed from the deck.

Sorry for my English. Is it suggestion understandable?

**Comment by trilz** [comment]
I think this would be a great feature. Just to add my personal experience, the group I play with likes the Promo cards but not the Promo corps of the base game. This is partially because our main experience was on TTS where it's shuffled into base game even when you don't check the box for fan made corps. So we would like to see Penguins, Asteroid, Snow Algae and Self Replicating Robots but would probably ban some or all the corps. This feature would provide a lot of flexibility in recreating that experience.

**Comment by alrusdi** [comment]
> So we would like to see Penguins, Asteroid, Snow Algae and Self Replicating Robots but would probably ban some or all the corps

You can do it already. We have corporations filter

**Comment by trilz** [comment]
> 
> 
> > So we would like to see Penguins, Asteroid, Snow Algae and Self Replicating Robots but would probably ban some or all the corps
> 
> You can do it already. We have corporations filter

Oh, wow. Bad at reading. Thanks.

Still would upvote the issue for playing cards, though. The same group I play with likes to sometimes just rotate out random cards because we think they are boring (Protected Habitats) or can get a bit out of hand (Terraforming Ganymede).
