### ISSUE TITLE
UX: Combine all info from all players into a single table 

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#1207]
These are many UX changes into one suggestion.

All player's info to look like: 
![red](https://user-images.githubusercontent.com/6917565/91042698-7f6ef780-e612-11ea-95d8-e2946ebf522b.png)

Current vs Suggested:
![boards](https://user-images.githubusercontent.com/6917565/91042427-02438280-e612-11ea-86c9-d82f20cd300a.png)

## Idea
All player's information to be on a single row (current player row is the bottom one).
This should significantly reduce the vertical scrolling when taking actions - less vertical space is used and the info is on the same row.

Example: 
Red can see all his resources and tags, along with the opponents right above, while all possible actions are right below. 
He doesn't need to scroll up to see the Tag Overview or to keep the Green tableau open to check his resources. 

## Changes
- Remove current player resources board
- Remove other players resources boards
- Remove current player Tags counter
- Remove other players Tags counters
- Remove "Turn Order" 
- Remove Tag Overview text

- Rework the resources boards (so they take less height) 
- Only played tags are displayed (identical to the current Tags counters)
- Add label "active" for the player currently playing
- Add label "passed" for every player that has passed
- Add icon "1" for the First Player this gen
- Sort the players (current player is last row and the player that plays after him is 1st row) to keep the Turn Order functionality.

**Comment by vincentneko** [comment]
This is wonderful !

**Comment by chosta** [comment]
Wunderbar!

**Comment by alrusdi** [comment]
Lovely! But we probably need to keep the current player resources bar sticked to the top of the window. It helps very much to make decisions when playing cards.

**Comment by jijiqw** [comment]
Cool! wow

**Comment by andylatto** [comment]
This looks great! I see that there is some way to show or hide other players' played cards, since the image has a "green's played cards", with an x to remove it. Once it's removed, how do you bring it back? It used to be done by clicking greens' box in the turn order row, but the turn order row is now gone. If the answer is that clicking a player's summary row shows their played cards, there should probably be text somewhere saying this, the way the current UI says "click on player name to see details". Other than that, I think this will eliminate lots of scrolling and speed up play a lot! I also appreciate having an indication of which players have passed, which was missing from the previous UI.

**Comment by chosta** [comment]
@andylatto I am currently working on a solution on what you mentioned. There are a couple of versions I'm testing for UI elements that might be used to prompt a player to click and view the cards of any other player.

**Comment by kevinb9n** [comment]
Looks like TR is missing from the redesign. imho, the best place to add it would be very near to the megacredits inv/prod, since I have to add those three numbers together to know how much money I'll have next turn.

**Comment by kevinb9n** [comment]
Cool, the TR is there now. I would still very weakly request it be moved to the left for the reason just above, but okay.

**Comment by alrusdi** [comment]
This is done. Lets' discuss any related problems in separate issues
