### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#1333]
Our server crashed when we played today. So we lost our game. It would be great if we can save progress and load it after crash. I think you can save progress after every generation (or every action) on disk.

**Comment by SliceOfBread** [comment]
I think this is related to #1110 If there was an executable log of the entire game, it would be (fairly) easy to implement crash recovery.

**Comment by pierrehilbert** [comment]
Hello @AlexBurkov,
This function already exists, it's what allow us to continue a game after a server restart on the heroku server.
If it doesn't work on your installation, it could be for many things and we will help you to find the root cause.
I think it's the same root cause with you issue #1331 so you should merge your issue.
