### ISSUE TITLE
Playwrites test flaky?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1388]
From the main branch:

Playwrights
       Can replay other player's event:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2

**Comment by kberg** [comment]
@nwai90 this seems to still be happening. https://github.com/bafolts/terraforming-mars/pull/1442/checks?check_run_id=1196738089

**Comment by bafolts** [comment]
I think I spot the issue here. If you happen to draw `TechnologyDemonstration` upon playing it will be removed from your hand throwing off the count by one.

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L1231
https://github.com/bafolts/terraforming-mars/blob/master/src/cards/community/Playwrights.ts#L43

Will put up fix.

**Comment by kberg** [comment]
It's back: https://github.com/bafolts/terraforming-mars/pull/1479/checks?check_run_id=1218531222

 1) Playwrights
       Can replay other player's event:

      AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at Context.<anonymous> (dist/tests/cards/community/Playwrights.spec.js:1:9452)

**Comment by bafolts** [comment]
We meet again.
