### ISSUE TITLE
Feature request: upgraded sidebar

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1419]
![TM side bar-01](https://user-images.githubusercontent.com/14239220/94623008-3b11ef80-0281-11eb-95a0-95db113c6a8c.png)

- Generation count (add max gen for solo mode)
- Global parameters
- Players' status (not necessary, less important)
- Fast mode indicator

**Comment by kevinb9n** [comment]
That is hot.

Would it be possible to reorder the player icons with the current generation start player on top, instead of needing the extra 1 symbol?

Also, I like the VCR buttons. But I would have said that the three states "my turn / waiting for my turn / out for the round" actually map pretty nicely to the VCR icons for "play / pause / stop", so what if we used those?  I'm aware that people who didn't grow up with literal VCRs as I did may be *less* familiar with the stop icon than the others, but... so what?

Again though, this would be awesome.

**Comment by kevinb9n** [comment]
Maybe consider some slight visual distinction for a parameter that is maxed... even I forget what the maxes are at times.

**Comment by vsrisuknimit** [comment]
@kevinb9n The idea is that we want the user icon to always be at the bottom, consistent with the resource table during the game. So we cannot have 1st player always on top.

**Comment by vsrisuknimit** [comment]
> Maybe consider some slight visual distinction for a parameter that is maxed... even I forget what the maxes are at times.

Perhaps a check mark instead of a number when a parameter is finished.

**Comment by vsrisuknimit** [comment]
Closing this with #1500 
Let's revisit the player color and turn order later if there is a demand.
