### ISSUE TITLE
Feature request: option for legacy UI

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1429]
Under settings, add an option to turn on or off legacy UI to replace the new design. Some players just enjoy the flat-design more.

1) Wait until the new design is more or less done.
2) Duplicate the assets folder to legacy-assets, replace all the new design icons with the legacy icons BUT make sure each and everyone of the images is of the exact same dimension as the new design, so they can be exchanged seamlessly. The legacy will be images rather than emojis/unicodes.
3) Have an option to pull assets from either of the two folders.

https://github.com/bafolts/terraforming-mars/tree/master/assets

**Comment by ssimeonoff** [comment]
This will require so much work, because the cards are done in a bad way (by me) and a lot of html has been changed in order to accommodate the new layout, so switching between styles is not simple.

**Comment by chosta** [comment]
Sadly, I must agree with @ssimeonoff
Adding new designs is a meticulous and time-consuming process. Even if the HTML + css from Simon was perfect (which it almost is) the switch to the old one would still take too much effort. I know for sure that everything new especially in the visual department, always raises eyebrows but I have a simple rule when it comes to these situations. **If there aren't people screaming "Bring back the old design now!" it means that the new one is excellent and it just needs a bit time to settle in**. It is because, we as humans, get attached to things and don't want to let go of them because we have to make the effort to adapt to the new norm. 
I also think that Flat vs. Skeumorphic design is something that will always cause a debate so we can keep this open for discussion and one day Flat may come back to rule the app. For now, unless someone really wants it back and puts the hours in it I don't see us going backwards.

**Comment by vsrisuknimit** [comment]
I will work on it. I will create identical graphics but flat so one can easily replace the entire assets folder.

**Comment by chosta** [comment]
> I will work on it. I will create identical graphics but flat so one can easily replace the entire assets folder.

You really don't like the new design, do you :)
Ok, then. Don't be shy to ask for help. Your determination is inspiring.

**Comment by vsrisuknimit** [comment]
@chosta I like most of it actually. I just think certain aspects are too distracting and less functional than before.

**Comment by kevinb9n** [comment]
You might consider looking for examples in history where a decision was made to support multiple UIs where the developers did not come to regret it. :-) Just a friendly observation.

**Comment by chosta** [comment]
Just to be clear. I don't think having a flat design is a bad idea. It's
the nature of the code that does not allow for a smooth transition/ switch.
If the components were done properly and we are slowly getting there, then
it wouldn't be a double effort. It's a more of a technical

**Comment by vsrisuknimit** [comment]
I have flat UI for myself if I want. Wait for @chosta to finish transferring the cards.
