### ISSUE TITLE
Feature request: show Turmoil event count

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1436]
![image](https://user-images.githubusercontent.com/14239220/94820165-24c57a00-03ce-11eb-93a0-486c453862cd.png)

![image](https://user-images.githubusercontent.com/14239220/94820237-3a3aa400-03ce-11eb-8473-7e7b295e352d.png)

Similar to milestones and awards. For the incoming event, show color boxes below the event with the current count up until maximum + influence.

This will be extremely useful especially for competitive events (who has most city tags and such).

**Comment by kevinb9n** [comment]
+1!

I think I would favor doing the full calculation of the exact number of resources/production/etc. the player stands to gain or lose if the generation ended at that moment. (I would go so far as to say that any event that looks at TR should use TR-1 for this purpose.)

Question: always show a gain as positive, loss as negative? Or follow the direction of the card wording?

Some complications with that approach:

* For Diversity, the raw tag count might be a more useful value then one that magically flips between 0 and 10 for perhaps mysterious reasons -- but the inconsistency may not be worth it

* Similarly for Revolution and Election the raw number that's being compared to opponents' would be most helpful.

* Red Influence, Sabotage, Global Dust Storm, Sponsored Projects, and Jovian Tax Rights each do multiple things. Now what? (In each case, I can make an argument that one of these values is the one more worth calculating, but it'd be weird/confusing anyway)

**Comment by vsrisuknimit** [comment]
Disagree with full calculation. People can do a simple multiplication by 2 or 3 if they need. 

Best to make it simple what is the most important count. Every event will just show one number for each player.
- Diversity: tag count + influence
- War on Earth: just count influence.
- Revolution: count earth tag + influence
- Ecosabotage: count influence
- Red Influence: number of set of 5 TRs above 10. (not showing influence, that can be read else where)
- Dust Storm: Building tag (max5) - influence.
- Sponsored Projects: count influence
- Jovian Tax Right: count colonies

**Comment by kevinb9n** [comment]
Question: how are casual players going to have any idea what the number means? This is an issue I think we'd need to resolve, no matter what choices we make for the calculations themselves.

Separately, back to the choices of those calculations... we have 8 cards that are special cases, but we have 28 cards that are the general case, in that it's totally feasible to do the full calculation, and I don't see why it shouldn't. That value seems the most helpful one to users, and it's also easy to learn/remember what the meaning of the value is.

But, since it's not possible or desirable for the 8 special cases, I wonder if you would consider styling the number differently in some way as a visual cue that it's not the same quantity you're usually seeing. Unfortunately, though, this alternative styling may not be noticed anyway, since you're never seeing it in comparison to the regular styling. (I am assuming, throughout all this, that we would not try to show these stats for anything but the immediately upcoming event, since guessing at future influence is super dodgy.)

**Comment by kevinb9n** [comment]
@nwai90 pointed out that we could go ahead and do just the 28 "easy" ones first. Since we should show only one event at a time (the current one), it won't have an inconsistent appearance at any time.
