### ISSUE TITLE
Smart payments UI widget

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#145]
I like how the payment widget works in official app.
How about to make something similar? It should be mostly mouse driven; automagically reduce MC value by current ratio of titanium, steel, heat and microbes. And look like this (may be):
![payments_widget](https://user-images.githubusercontent.com/394311/71462557-6ab53800-27d5-11ea-9cdb-8b79dc44d050.png)

What do you think?

**Comment by vincentneko** [comment]
For cards that can be payed with steel or titanium or heat or microbes, the widget should use them by default but the player should be able to change the amount.

For instance, if I have 2 steel, Peroxide Power should How to pay should be defaulted to:
M€ : 3
Steel : 2

But now let's assume I also have Electro Catapult card, I will switch How to pay to:
M€ : 5
Steel : 1

in order to keep 1 steel for Electro Catapult.

**Comment by alrusdi** [comment]
No, we will suggest only amount of M€ as we do it now
But if user increases amount of steel to spend we are automatically reduce megacredits

**Comment by alrusdi** [comment]
I mean, we can't know user plans for other resources...

**Comment by alrusdi** [comment]
Or we can implement both variants, but with ability to change it in Preferences

**Comment by vincentneko** [comment]
Having the ability to change behavior in Preferences is great.
90% of the time, I use steel or titanium to pay for cards if I have some in stock.

**Comment by alrusdi** [comment]
Next step will be that preferences option to auto assign as many as possible non-money resources to pay by

**Comment by alrusdi** [comment]
@vincentneko how it's important for you to automatically assign other-than-MC-resources to pay by? I dislike of how complex will be component code for this feature. Can we live without it :-) ?

**Comment by vincentneko** [comment]
It's really not important. I can easily live without it.

**Comment by alrusdi** [comment]
Ok, then let's close this issue
