### ISSUE TITLE
Bug(?): Lava Tube Settlement can't be played with all vulcanic areas blocked

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#1450]
Hi,

like the title states: I've linked my _Lava Tube Settlement_ with my _Self-Replicating Robots_ and doesn't seem to be able to play the card despite the fact that I definately have the ressources to do so. As you can see in the screenshot the four volcanic areas are blocked by other tiles or tokens and the Lava Tube Settlement does not show up in the row of cards to play:

https://abload.de/img/scr0wjbk.png

I'm under the impression that whenever a specific placement rule like this cannot be met you are allowed to place the tile anywhere on the board - at least I'm pretty sure that it worked this way in previous rounds.

Cheers!

**Comment by nwai90** [comment]
@ap3h3ad That doesn't seem correct as the official ruling states otherwise. See the following:

https://boardgamegeek.com/thread/1953628/lava-tube-settlement-wording
https://boardgamegeek.com/thread/2106043/lava-tube-settlement-placement-restrictions
https://www.reddit.com/r/boardgames/comments/f1vb29/terraforming_mars_lava_flows/fhh5zgc/

**Comment by ap3h3ad** [comment]
Hi,

thanks for the clarification. I wasn't aware that it was indeed a special rule on the Hellas map.

Cheers.
