### ISSUE TITLE
MARS UNIVERSITY and OLYMPUS CONFERENCE

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#148]
Having both card played cause a bug to occur when playing another science tag card.

I think it's because both events are resolved at the same time.

A error message is displayed (cannot remember what is was..) and cards actions do not complete. It is not blocking the game.

**Comment by alrusdi** [comment]
We are also hit this problem last time. I don't know how to solve it. May be @bafolts has an ideas?

**Comment by bafolts** [comment]
I am assuming this issue is due to using an `OrOptions` inside an `onCardPlayed`. Using an `OrOptions` as a child of an `AndOptions` must throw an error somewhere. I will look into this. Rewriting `MarsUniversity` to not use `OrOptions` would be straight forward. Rewriting `OlympusConference` isn't as straight forward as the `OrOptions` works well for that card. May have to create a `SelectOneValue` instead of `OrOptions` or fix the underlying issue.

**Comment by bafolts** [comment]
I see the problem Any `OrOptions` inside an `AndOptions` should fail since we only take the first item selected. When using a `SelectCard` inside an `OrOptions` we will drop the selected card leading to an error processing input thrown.

https://github.com/bafolts/terraforming-mars/blob/master/src/components/AndOptions.ts#L24

**Comment by alrusdi** [comment]
We hope it fixed now thanks to @bafolts black magic :-)
