### ISSUE TITLE
Consider offering one variant to remove "take-that" element

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1492]
Filing this, but if no one else wants it, then nothing to worry.

Many groups don't like the "take that" mechanic in any game, not just because it's an attack and attacks feel bad, but that the player freely *chooses* who to hurt, and usually does so based on a flawed guess at who they think seems to be winning. As a result, part of winning is trying to "seem not to be winning". It also brings in serious metagaming.

In any case, for people who are totally fine with all that, there is no problem. But I think it would be nice if one variant option was offered for removing this aspect of the game.

But I don't favor variants that remove attacks from game, because then I think plant strategies would need to be rebalanced.

What I would favor is the change that *changes the game the least*, and that is to only remove the targeting, not the attacks. That's right, I'm talking about AoE attacks. :-)

Say I play a card that will remove N resources or reduce production by N. Then:

* For each opponent that I *can* attack this way, remove/reduce by 1 from each, clockwise from me, stopping if N is reached.
* Repeat.

This still preserves a lot of the risks inherent in the game. For example if I'm going to have 7 plants next gen and an opponent will have 1 (or 9), I'll know that this is dangerous because I will get the full force of any attack. I think the fact that attacks play out deterministically actually might even make the game more tactical.

This scheme would dictate which player Ants/Predators must take from, but the attacker should still get to choose which card.

I would rather see NO variants for this than to end up with 6 different variants for it though. The question is whether the community could get consensus around one and stick with that.

**Comment by pocc** [comment]
This is an interesting take on resource removal. It's possible to remove cards from a game as an option, but you're suggesting something else. 

I think it will be hard to remove metagaming from Terraforming Mars. For example, if I have one of the production cards that gives me a tile to place, and I can disrupt another player's cities/greeneries by placing it strategically, I probably will. There's not really a way to have an "AoE" tile placement unless you get as many tiles as players. 

WGT is also semi-antagonistic towards specific players because you usually increase whichever rating your opponent has most production in (oceans, oxygen/plants, temp/heat).

I.e. there are many "take-that" elements, and removing all of them changes the game.

**Comment by kevinb9n** [comment]
Good points. Of course the game is still competitive, and we wouldn't want to make it not so.

I'd claim there is, nevertheless, a *special* category for actions that *purely* harm another player, whom you can *freely* choose. It's the purest form of "take-that" and for groups that dislike take-that mechanics, these are the kind they're talking about. In this game, it's the remove-resources and reduce-production actions. (I wouldn't even include Banned Delegate because you have clear motivations to improve your own standing in the assembly.)

Simply removing all attack cards from the game would be an option if we do #1440. But it's a good example of a bad fix that has unintended consequences: so many Big Terraforming cards go away, cards like Optimal Aerobraking become useless... I don't think I would want to play this way.

**Comment by kevinb9n** [comment]
Note that some provision would have to be made for Mons.
