### ISSUE TITLE
Noctis City not placed correctly

### ISSUE THREAD

**Issue by rstanculescu** [bafolts/terraforming-mars#1539]
In a recent game I played Noctis City on the base map, and instead of it being auto-placed it let me select any valid city spot (but not the Noctis space). There are no other city placed adjacent to Noctis either. See image below, with Noctis City tile circled in red.

![noctis](https://user-images.githubusercontent.com/1013778/95436488-8badda80-095c-11eb-90de-1c83105f4171.png)

**Comment by bafolts** [comment]
We only check for the board name to auto place the tile and as far as I can tell it is being set properly from the create game form.

https://github.com/bafolts/terraforming-mars/blob/master/src/cards/NoctisCity.ts#L32

**Comment by rstanculescu** [comment]
Ok, I'll ask the person who runs the server I'm on to check the code, thanks.

**Comment by bafolts** [comment]
The latest commit hash of the version being ran and a dump of the game JSON would be helpful if available.

**Comment by pocc** [comment]
This is my server, mars.ross.gg on 60855999a984444a1c3b175a0f041196fa762b4c being 3 days old from master. Do games get deleted after completion? I can't find the game.

**Comment by pocc** [comment]
These are the settings it started with

```
board   =   random
cardsBlackList   =   []
colonies   =   False
communityCardsOption   =   False
corporateEra   =   True
customColoniesList   =   []
customCorporationsList   =   []
draftVariant   =   True
fastModeOption   =   False
includeVenusMA   =   True
initialDraft   =   False
prelude   =   True
promoCardsOption   =   False
randomMA   =   True
removeNegativeGlobalEventsOption   =   False
seed   =   0.39429134905651575
showOtherPlayersVP   =   True
shuffleMapOption   =   False
solarPhaseOption   =   True
soloTR   =   False
startingCorporations   =   3
turmoil   =   False
undoOption   =   True
venusNext   =   True
```

**Comment by bafolts** [comment]
Games shouldn't get deleted unless they are older than the limit. If somehow we ended up with `random` as the `game.boardName` this would happen as the board name would not be `tharsis`. I can't spot how that would end up getting stored but can take another look.

**Comment by Lynesth** [comment]
I confirm that the issue happens when `/game` receives a board equal to "random".
You can also notice that in that case, the map legend disappeared:
![firefox_2020-10-11_13-57-18](https://user-images.githubusercontent.com/5318258/95669210-b3ee4100-0bc9-11eb-826e-5cf9b8677d07.png)

Since the change from "random" to 1 of the 3 maps is made on the client side there might have been an issue at that time and the actual word "random" was sent instead.
https://github.com/bafolts/terraforming-mars/blob/cb4a6e9649e77e0bcbcb2a98b8f3b9cac9826e15/src/components/CreateGameForm.ts#L210-L213

Maybe we should make that check and change in the `createGame` function of server.ts ?

**Comment by kberg** [comment]
I rewrote the rules for board placement, and it's entirely possible I broke
this. If I can look at this in about 10 hours I can make a good effort at
fixing it. That or rollback my board refactoring.

>

**Comment by bafolts** [comment]
I would be surprised if the board placement broke this. The check on `NoctisCity.ts` has been checking that `game.gameOptions.boardName === BoardName.ORIGINAL` since 2020-09-06. My guess is it was somehow introduced when `gameOptions` was changed with:

https://github.com/bafolts/terraforming-mars/commit/53cd664b2f951ee4f946612dbf2bb9f345e7a455

**Comment by bafolts** [comment]
Looking at the postgres data there are records with `random` as the `boardName` stored.

```
terraforming-mars::DATABASE=> SELECT count(*) FROM games WHERE game LIKE '%"boardName":"random"%';
 count 
-------
    19
(1 row)
```

None of them appear to be cloned games.

**Comment by bafolts** [comment]
The change on the client side is changing the vue data component board property which is going to use a setter and getter provided by vuejs. Moving the mapping from "random" to a random board on the server time being should be a good change and most likely fix this. The issue today could be browser related depending on how vue is handling the data property change.
