### ISSUE TITLE
Recyclon/Splice interaction

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1577]
Here's what I did and what I expected to happen:

1. Green plays Splice, receives 44+2 MC, then buys 1 card - balance 43 MC [EDIT: nope, 45]
2. Red plays Recyclon, receives 38 MC and 1 microbe, then buys 1 card - balance 35 MC
3. Splice effect activates
 (a) Red should be prompted to choose 2 MC or 1 microbe
 (b) Green then receives 2 MC - balance 45 MC

What I'm seeing instead is that Red gets nothing and Green somehow has 47 MC. It is as if Red's bonus was just given to Green instead. [EDIT: nope, Red's bonus is just missing.]

I think Red is "supposed" to get to choose. (To get SUPER-technical, while they do they should only know the corps of the players before them in turn order, none after.)

AFAICT this is the only case where the corp round has to be interrupted for a player choice. Even worse it's not *that* player's choice. I think it would be fair to house-rule that Red doesn't get to choose, but then which choice would the game make for them?

I left the game suspended at that point so you can verify:
https://terraforming-mars.herokuapp.com/game?id=977b35a970b6

**Comment by Lynesth** [comment]
When playing Splice, Green receives 4 MC, not 2 (it triggers both effects).
The issue here is that Red is not getting anything.

And that's linked to the fact that players play their Corp in the order they were defined (player 1, then player 2, etc) instead of starting with the first player (or it could be in the order they validate their initial cards, not sure yet).
So in this case, Red actually played his Corp and then Green played his.

We need to fix that. I'll try to work on it later today.

**Comment by kevinb9n** [comment]
@Lynesth ahh, whooops! Thanks.
I think if the corps had processed in the wrong order, though, that would show up as Green still only having 45 on their first turn.

**Comment by Lynesth** [comment]
Forget my comment above, things are happening in the correct order.
You were correct, there's indeed an bug with Splice when reacting to Recyclon (to a Microbe Corporate card that can gather Microbes actually).
I'm pushing a fix for it.
