### ISSUE TITLE
Pluto massively slows game down

### ISSUE THREAD

**Issue by kyshantry** [bafolts/terraforming-mars#1647]
Any chance we can have players simultaneously discard to pluto for the colony bonus? As it is, having pluto in the game slows a game down by ~15-20 minutes because of the sequential discards. 

Thanks!

**Comment by chosta** [comment]
Yes, we absolutely have to do something about it. I was tinkering with
notifications, not sure about simultaneous discard though. @bafolts what is
your take on this?

**Comment by bafolts** [comment]
I don't think this would require too much work. Every player already picks their initial cards simultaneously.

**Comment by kyshantry** [comment]
Yeah, it seems like you could do the same here, would be an absolutely
massive qol improvement

**Comment by funkybaboon** [comment]
👍 for this. Yesterday and on several games more I have witnessed that people do miss that they have to discard a card because someone flew to pluto and they have a colony there. They're probably doing something else, f.ex. in my game yesterday someone played another game at the same time 🙃.

Suggestion: If it's currently not your turn, but you have to discard, play the "It's your turn" sound and in the favicon show that their attention is required.
