### ISSUE TITLE
Many unexpected server response this afternoon despite no recent merge commit

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1660]
Many users mentioned they encountered 'unexpected server response' multiple times today despite no recent merge commit. 

Tagging @bafolts . Is Heroku being weird in general today?

**Comment by bafolts** [comment]
Nothing in the logs or the heroku metrics would indicate to me there was an issue today. If you were playing 4-5 hours ago a lot of commits would have made there way out. We could reconsider when the heroku instance gets deployed. If we posted a date and time the server was going to restart that would give players time to finish their games. The restart mechanism is most likely interrupting games right now.

Instead of deploying on every commit to the default branch what would work? I could manually deploy once a week or once a day. We can post the time on the README.md.

**Comment by chosta** [comment]
We always recommend hosting personal servers on heroku whenever we get a
complaint about a server crash (in diacord). It takes 5 minutes and people
started doing it consciously.
I'm against fixed times as the demo is run personally by @bafolts and
should not be considered official. People have a lot of games without
problem but the inevitable bugs appear now and then. Instead we should
focus on a rollback functionality that restores a game to a specific
generation and also maybe having heroku error logs accessible to all devs.
This approach is beneficial for the devs as players are kind of doing the
QA for us. They just need to realize that things might break. My 5 cents.

**Comment by vsrisuknimit** [comment]
Against fixed time merge as well. I personally think the games crashing encourage folks to host their own server as @chosta said.

Folks on Discord has a bot command ($crash) to check the recent merge time. 

@bafolts I crosschecked with the crash time with merge time. They do not coincide. That is why I asked about Heroku.

**Comment by bafolts** [comment]
@chosta I added you as a "collaborator" on the heroku instance. I am not sure what permissions that grants you. The documentation claims you should have access to most things. It also claims you could scale resources which is unfortunate. Please remember I am floating the paid instance! If others want access to the heroku instance please email me.

**Comment by chosta** [comment]
@bafolts thanks! I will be careful to not ramp up the bill I promise :)
