### ISSUE TITLE
Encapsulate JSONification.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1704]
https://github.com/bafolts/terraforming-mars/pull/1679#discussion_r509342212
Move JSON.stringify(game, game.replacer) to a toJSON() function so we don't have to copy this logic and have replacer be public.

**Comment by bafolts** [comment]
I will manually write out the JSON here to leverage `SerializedGame`. While starting on this I am already spotting areas where we are de-serializing data in a different type than we serialize. Also places where we serialize `Player` when we should be using `PlayerId`.

**Comment by bafolts** [comment]
So an update here. I am adding a `serialize()` function to most classes which returns the equivalent `Serialized*`. With this in place I think we will fix storing and retrieving of games from database! I will attempt to get the deferred actions coming in as well instead of wiping them. I should have something by end of the week. The goal is to not break any currently saved games during the transition as well. Want to have some interface through typescript so that if a property is added or removed from `FooClass` that `SerializedFooClass` requires updating it's type.
