### ISSUE TITLE
Turmoil: Don't include party leader in the delegate count

### ISSUE THREAD

**Issue by cdekker** [bafolts/terraforming-mars#1722]
Maybe this is subjective, but I find it not very intuitive.

So game rules give you 1 influence each for:

* Being the chair
* Being the dominant party leader
* Having at least one non-leader delegate in the dominant party.

Each of these 3 are shown in their unique frame. However, the party leader is shown and counted in the delegate frame as well. This has lead me incorrectly assume I have 2 influence from party leader and delegates, while only having party leader.

My suggestion: Do not include the party leader in the delegate count. If you get supplanted by a different player, you move back from party leader down into the delegate frame.

**Comment by kevinb9n** [comment]
fwiw, I have the same concern. The advantage that I can see of the current approach is it's easier to tell when adding a delegate will cause a leadership takeover. Since there's arguments on both sides, I feel like it should just resemble how an IRL game works - you don't see your party leader twice. I think the current way is something that every new user will always have to trip on a bit and then get used to.

**Comment by vsrisuknimit** [comment]
Disagree. There is no need to count the influence, the web app already does that for you in the table. 

The app also does not mimic the physical game directly. Rather than having multiple meeple of one color in one party, it just uses a number on the meeple instead. This number representing the total number of delegates from that one color. That total number makes a lot more sense than having to add the party leader again.

What we could do if necessary is to shrink the party leader delegate icon even smaller so the delegate icon there does not look similar to the delegates in the party.

**Comment by otolabqu** [comment]
A different icon could be used for the leader, for example a crown coloured with the leading player's color.
