### ISSUE TITLE
Feature Request: Timer / clock

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#1824]
Hi,
Maybe there could be build in timer? It could just measure how long every player has been thinking. It would not have any effect in game, however slower players would get motivation to make turns faster. (I'm always playing board version with timers).
Thanks!

**Comment by alrusdi** [comment]
Some ideas:
Each player has configurable amount of time for the whole game. Let's say 30mins
Each action has given time to finish without penalty, remaining time decreases play time of given player.
Game can be setup with 3 additional variants
1) No time penalty - just show the timers
2) Time penalty (reduce VP for each N overspent seconds) 
3) Time bound game. When overall time of the game is finished - this generation is last generation of the game no matter if global params are not upped.

All time calculations must be done on serverside
Additionaly we can use player time as second tie breaker for the end of the game

**Comment by kberg** [comment]
I would not object to a game clock!

>

**Comment by bafolts** [comment]
A first step could be to display the time. From there the feature could expand.

**Comment by funkybaboon** [comment]
👍 for just displaying the time. 

I would rather have a game option for a Time Bonus, similar like an award: The player with the least time spent gets 5 extra points and the player with the second least time spent gets 2 extra points.

**Comment by kevinb9n** [comment]
Just display the total time used so far. It will probably make all the difference you need.

A case could be made for different treatments for simultaneous actions, but I think just accruing whatever time each player actually spent making their decision will still work (even though only one of them might have actually held anything up).

Having the client show an opponent's clock actively ticking while waiting for that player's move would probably introduce complexities; the client's idea of that clock can get off. For one thing I think it would be important to stop the ticking if the client loses contact with the server. In fact, users would want to be alerted that contact was lost because it means that their own clock might be ticking without their knowledge.
