### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by gsjostrom** [bafolts/terraforming-mars#1876]
I pulled the latest to my own server instance but the app will not launch, I get a generic 'Application Error' page. Log file attached.
[HerokuLog.txt](https://github.com/bafolts/terraforming-mars/files/5524814/HerokuLog.txt)

**Comment by bafolts** [comment]
Something seems to be taking heroku machines more than 60 seconds to build. If you click to deploy again it could work. Will need to see how to increase the timeout.

```
2020-11-11T14:47:50.497683+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

**Comment by bafolts** [comment]
This could be due to upgrading to typescript 4 or one of the many npm dependencies we have growing and taking larger to download. Since heroku wants us to bind to $PORT as soon as possible we should be able to bind while waiting on webpack and the client side typescript to compile. At a minimum the `server.ts` has to be compiled so we can start it listening. It would know if `main.js` existed and could collect requests until `main.js` has been build by webpack. Assuming that downloading all dependencies wasn't taking a minute this would buy time. The `server.ts` is really different than the rest of the javascript as it is the only class which should use the `node` type. Everything else could run on client and shouldn't use node types.

**Comment by bafolts** [comment]
For the time being you have to manually deploy until it finishes within the timeout until we can determine what has changed to put us over this limit. We were never timing how long this took so we could have been flirting with 60 seconds and someone put us over recently. I have been deploying manually for `terraforming-mars.herokuapp.com` and haven't had an issue since first deploying a version which changed typescript from 3 to 4. If heroku is caching `node_modules` in some way it could also be related to that first change over.

**Comment by gsjostrom** [comment]
How do you manually deploy?

**Comment by bafolts** [comment]
I use the GUI from the heroku website.

https://devcenter.heroku.com/articles/github-integration#manual-deploys

**Comment by Lynesth** [comment]
@bafolts As they mention [here](https://help.heroku.com/P1AVPANS/why-is-my-node-js-app-crashing-with-an-r10-error), it could be due to `npm start` taking more than 60s. Can we change `npm start` to simply sart the server and use `postinstall` to `npm run build` as they suggest ?

**Comment by bafolts** [comment]
That should work. Anyone using `npm start` locally will need to run `npm build` first. Ideally the `postinstall` would only run in production environments to not impact developers.

**Comment by bafolts** [comment]
@Lynesth thanks for that suggestion. It does seem heroku runs `build` and then doesn't take down the running application until build passes. It then runs `npm start`. This change should also make the game restarts much smoother on people playing games as the switchover is much faster now.
