### ISSUE TITLE
Development server code refresh

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1887]
For me, changing code and running the browser to see if things work takes too much time at the moment. I realise that `tsc` needs to compile and that is the reality but now I have to wait at least 30 seconds for `npm run build` to finish and run `npm start`. For backend tasks it is kind of OK, but frontend sometimes needs a bit more refreshing than usual and it is time-consuming and annoying. 
Do you have any suggestions on how we can speed up the process. Maybe add a script that only watches `tsc` and `css` changes and updates upon code change. I think `tsc` has a `watch` option but I'm open to suggestions from more experienced `ts` users.

**Comment by bafolts** [comment]
All of the client side javascript goes through `main.js` which `webpack` builds for us. This is always building in production mode and compressing the javascript. As a shot term solution we should only run the production mode when `NODE_ENV` production is set.

https://github.com/bafolts/terraforming-mars/blob/master/webpack.config.js#L7

Should also only include the `CompressionPlugin` when `NODE_ENV` production. This change should buy some time from the overall time of `npm run build`.

In terms of watching file changes we will need to have `webpack` watching as well so that it can re-build the bundle.

https://webpack.js.org/configuration/watch/

It should be easy enough to get this working when not in dev mode. I agree that it takes too much time and it will make front end improvements cumbersome.

We need better separate between what is server side and client side and this change should help with that. When building for only server side changes it is also time consuming waiting for the CSS to build each time. There is `npm run compile` which can be used to only compile the typescript for server side changes but that isn't helpful on front end.

I can check this out. I don't think it would take long to get it wired together. Everything has been geared towards the "production" heroku site but now need to consider the _production_ environment versus local developers.

**Comment by chosta** [comment]
Thanks for the comments. I agree we should find a way to separate dev builds and probably using some webpack plugin (I've done this with react). I tried `compile` only but as you mentioned its not enough. I'm ok with not having a `start:watch` script but maybe a quicker `tsc + less` compile command would do it for me.

**Comment by bafolts** [comment]
@chosta add `watch: true` to the end of `webpack.config.js`. When you then run `npm run webpack` webpack should stay running as a process. If you then make vue changes and run `npm run compile` you should see webpack re-generate the `main.js`. Refreshing the page should then show your change. Is `start:watch` standard practice? We could set `watch:true` if `start:watch` were provided as the run script.

**Comment by bafolts** [comment]
If you add `watch: true` to `webpack.config.js` and leave `npm run webpack` running this goal will be accomplished. Closing.
