### ISSUE TITLE
Can Robotic Workforce work on Ares' Capital card?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1969]
A bug report on Discord suggested it could not be done. https://discord.com/channels/737945098695999559/742721510376210583/782125546213081108

**Comment by andylatto** [comment]
Very simple fix to that one; the builderCardNames list in RoboticWorkforce.ts includes CAPITAL, but doesn't include CAPITAL_ARES. There may be other Ares cards missing from this list; I'll check.

**Comment by andylatto** [comment]
Yep. BIOFERTILIZER_FACILITY, OCEAN_CITY, OCEAN_FARM, COMMERCIAL_DISTRICT_ARES, SOLAR_FARM, MINING_AREA_ARES, MINING_RIGHTS_ARES, MOHOLE_AREA_ARES, and NATURAL_PRESERVE_ARES. Several of these also need to get added to lists in the canPlay code to check that the player has enough energy production to use, the mining cards need to have the same special-casing as their non-ares counterparts.SOLAR_FARM is a little trickier, since the production this card produces is variable.

**Comment by kberg** [comment]
Oh, man, Solar Farm. >:-(

**Comment by Lynesth** [comment]
Fixed by #1974.
