### ISSUE TITLE
App stops after building db

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#2041]
When starting the app (`npm start`) with no database file present, it will create it and then exit instead of booting. Have to restart it once more.

**Comment by bafolts** [comment]
The database queries run asynchronously but the code is written as if the queries are running synchronously. What happens here is the database file is created after we run the query to get games. The callback which then starts the server is never called.

https://github.com/bafolts/terraforming-mars/blob/main/src/database/SQLite.ts#L47

There is an error throw and no results. The fix for this will require passing a callback to `Database.getInstance` that gets called once the instance has loaded.

When I added an error handler following error was seen:

```
SQLite:getGames { [Error: SQLITE_ERROR: no such table: games] errno: 1, code: 'SQLITE_ERROR' }
error loading all games { [Error: SQLITE_ERROR: no such table: games] errno: 1, code: 'SQLITE_ERROR' }
```

**Comment by alrusdi** [comment]
May be it is the time to move to async/await syntax?

**Comment by Lynesth** [comment]
Fixed.
