### ISSUE TITLE
How do Game instances actually work?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2085]
I'm starting to look at how games are created and managed, and of course what I see is that a Game instance, once created, isn't replaced with a new instance of Game, but instead updated with `loadFromJSON` which of course you know I've been looking at removing.

So, I could work on replacing all of these with freshly-created instances of Game -- one would replace the other. But, is that going to work? As far as I can tell, everything hinges on the game that is served when someone loads the game. So, if I replace the way games are created, is it just a matter of futzing with GameLoader to make sure its cache is accurate?

Or am I going to have to do something even more weird?

**Comment by kberg** [comment]
Paging @bafolts

**Comment by bafolts** [comment]
I would think replacing the game in `GameLoader` would work fine. Javascript is single threaded. Unlike a multi threaded environment we don't need to worry about potentially replacing the game instance while we are working through some player request which would be updating it's state. All of the player actions happen synchronously so they will run to completion until they are done updating the player or game instances they are provided. The undo action is the only action where during the action the game instance and player instance's we have will become orphans as they get replaced. This is already happening with the player instances today so I wouldn't expect it to be a problem with games.

**Comment by kberg** [comment]
I have to figure out more about async and wait works because my brain knows
how Java concurrency works (I read a whole book about it.) But not how a
single-threaded asynchronous framework works. Do you have a good basic
reference?

>

**Comment by bafolts** [comment]
Both `async` and `await` are syntactic sugar. At any point javascript is single threaded. When javascript appears to be doing things asynchronously this is due to the event loop. For this project most of the asynchronous code is handled through i/o when the `http` modules gets a request so we don't have many (if any) usages of `setTimeout` or `setInterval` which are two functions where you can schedule code to run at a later time (it gets placed on the event loop). Anything appearing to run asynchronously is a magicians trick. All things are coming from event loop.

https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args
