### ISSUE TITLE
Bug: Games at setup don't survive server sleep on a DB connected server

### ISSUE THREAD

**Issue by lomky** [bafolts/terraforming-mars#2109]
Server Setup: 
Heroku app with postgres dyno spun up & connected via env var

Steps to recreate:
 - Setup and start a multiplayer game through player link creation, but no further
 - Allow the server to idle and go to sleep
 - Attempt to access either the `game` or `player` link
 - Receive `Unexpected server response`

![image](https://user-images.githubusercontent.com/6129479/102018501-8d6c9380-3d3b-11eb-979d-7835f6e555f4.png) |

I confirmed in the database that the game has been saved
![image](https://user-images.githubusercontent.com/6129479/102018529-be4cc880-3d3b-11eb-8cfc-1cd368b4029a.png)

I set up test games at various other points (just finished corp & card selection, first turns all taken) - they do not encounter this issue. They also have multiple save entries in the database, as you would expect.

**Comment by bafolts** [comment]
I will label this as an enhancement only because I believe this was the original intentions. Since we have the game in the database though there is no reason we can't salvage it in this situation.

https://github.com/bafolts/terraforming-mars/blob/main/src/database/PostgreSQL.ts#L70

If I remember this was done because of how the code happened to work probably while de-serializing a game from the database. It makes sense to me to get this to work though.

**Comment by lomky** [comment]
Noted! For now we'll just make sure to finish setup before the server goes idle.

For understanding the actual use case, my friend is playing with another friend in Europe, so they are playing (very) asynchronously.

---

Also, I confirmed that this happens at any point during the setup turns:
  - Setup and start a multiplayer game through player link creation
  - One player finishes their setup
  - Allow the server to idle and go to sleep
  - Attempt to access either the game or player link
  - Receive Unexpected server response

In this situation, no additional database save was created when the one player did their setup.
