### ISSUE TITLE
Feature: Player boards minor rework

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#2150]
![1](https://user-images.githubusercontent.com/6917565/102722118-45cba600-42ff-11eb-8459-89c540c7eca7.png)

1. The main idea is to add a header to the player boards.
It will add more height, I know...

2.  The secondary idea is to combine to timers and player state labels in a single element
When a player is "active" the timer is ticking. 

3. Minor UI changes as colours and reordering 
More black and less white text - corporations and player names (easier for the eyes)

4. As a future feature, the toggle button TOGGLE TAGS VIEW to have a 3rd state showing the discounts (displayed in that header space)
![2](https://user-images.githubusercontent.com/6917565/102722119-46643c80-42ff-11eb-8274-7ff6b2416c67.png)

5. (optional) More info in the header
Since there is free space (between the corporation an the discounts bar), more info items can be added there. 
Example: The played cards count can be displayed there instead with a more detail overview.
![3](https://user-images.githubusercontent.com/6917565/102722657-dd7ec380-4302-11eb-91d9-8bb187c6544e.png)
Red has played 1 of each type of project cards and has 2 played card that can be activated (active action from corporations corporations are included).

**Comment by chosta** [comment]
Good stuff. I'm doing it next week!

**Comment by kevinb9n** [comment]
> 4. As a future feature, the toggle button TOGGLE TAGS VIEW to have a 3rd state showing the discounts (displayed in that header space)
>    ![2](https://user-images.githubusercontent.com/6917565/102722119-46643c80-42ff-11eb-8274-7ff6b2416c67.png)

This is very good.
It's fine that it's discounts only. I'd love to have a tracker for when-play effects one day, but enough of them aren't strictly tag-based that it can't be shoehorned into this model anyway. We can forget about them for now.

In addition to per-tag discounts there are of course per-card discounts, from four cards which can total down to -6. I think it would work to show that value in the same way as these, just to the left of them, right above the "cards in hand" count.

The one remaining type of card discount is also per-card, but conditional (Cutting Edge), so meh, it'll just be a stealth discount, seems fine to me.

Btw #1426 talks about drawing a separation between the tags (up to the city tag) and everything else (after that). I do think that would help players of Aridor and Diversity Support (and the Diversity global event) to understand them correctly.


>    Since there is free space (between the corporation an the discounts bar), more info items can be added there.
>    Example: The played cards count can be displayed there instead with a more detail overview.
>    ![3](https://user-images.githubusercontent.com/6917565/102722657-dd7ec380-4302-11eb-91d9-8bb187c6544e.png)

I will of course beg as I did in #2058 that blue include yellow, and green include pink, as they are entirely equivalent in function. I think it's still fine to color them as they are.

The orange number duplicates what's already shown under the yellow "event" symbol. If we only want one, I think the latter is better because it matches card iconography, even for the Legend milestone I think.

Anyway this will be awesome.

**Comment by kevinb9n** [comment]
FYI I think the only per-tag discounts are on the first 7 tags in the list (and not Jovian at that).

One of the ruling policies in Political Agendas provides a -2 discount on space tags (well, it says it's per card, but it should be the same as everything else and anyway there are no 2-space-tag project cards anyway).  So you would need to decide whether that should be accounted for in here or not.

One idea: do account it, but change the color of the numbers to suggest that the value is temporary.

For that matter, suppose I have -1 on all cards (Research Outpost) but then I play Indentured Workers; that -1 could change to -9 but again be in a color indicating temporariness.

**Comment by chosta** [comment]
#2150 should close this one but I'm pretty sure it's not going to be the end of it :)
