### ISSUE TITLE
RFC: how to deal with Moon costs

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2176]
**Sorry for the long post. I'm seeking approval to change `Card.cost` from `number` to `number|Fees` unless you have a better idea.**

Look at this example card:

![image](https://user-images.githubusercontent.com/413481/103013526-4c2e6d80-450b-11eb-9ffa-ce1a01bddc5a.png)

It has a MC cost, but also in its action it has a resource cost of 1 titanium. This sort of additional resource cost is typical in The Moon cards. And while I can get most of the way there by implementing a custom `Fees` class (see below, currently only tracking paying additional MCs, steel, titanium and energy production)

and impliementing cards like so:

```
export class MareSerenitatisMine implements IProjectCard {
  public cost = 21;
  public fees = Fees.builder().titanium(2).steel(1);
  public canPlay(player: Player, _game: Game): boolean {
    return this.fees.canAfford(player);
  }

  public play(player: Player, game: Game) {
    this.fees.deduct(player);
    ...
  }
}
```

that only gets me most of the way there. Think of `Player.canAfford`. Envision a card with a titanium fee and also a space card -- well, will canAfford take both of those into account? It won't.

I can see three ways of dealing with this:

1. Temporarily deduct Fees from a Player before calling `canAfford`
2. updating `canAfford`'s first parameter

from `public canAfford(cost: number, game, canUseSteel, canUseTitanium, canUseFloaters, canUseMicrobes): boolean {`
to `public canAfford(cost: number | Fees, game, canUseSteel, canUseTitanium, canUseFloaters, canUseMicrobes): boolean {`

3. Change Card.cost from `number` to `number | Fees`.

The new Moon standard projects have similar costs:

![image](https://user-images.githubusercontent.com/413481/103014221-69177080-450c-11eb-8bac-c0cb826e799c.png)

18MC + 1 unit of steel to place a road.
20MC + 1 unit of titanium to place a mine
22MC + 1 unit of titanium to place a colony

From the point of view of this lone expansion, the thing is to change Card.cost to `number | Fees`, and also `player.canAfford`. But this seems pretty Moon-centric. I just think the alternatives can be pretty tricky to get right.

```
export class Fees {
  private mcunits: number = 0;
  private tunits: number = 0;
  private sunits: number = 0;
  private eprod: number = 0;

  public static builder(): Fees { return new Fees(); }
  public megacredits(val: number): Fees { this.mcunits = val; return this; }
  public titanium(val: number): Fees { this.tunits = val; return this; }
  public steel(val: number): Fees { this.sunits = val; return this; }
  public energyProduction(val: number): Fees { this.eprod = val; return this; }

  public canAfford(player: Player): boolean {
    return player.megaCredits >= this.mcunits &&
      player.titanium >= this.tunits &&
      player.steel >= this.sunits &&
      player.getProduction(Resources.ENERGY) >= this.eprod;
  }
  public deduct(player: Player) {
    player.megaCredits -= this.mcunits;
    player.titanium -= this.tunits;
    player.steel -= this.sunits;
    if (this.eprod > 0) {
      player.addProduction(Resources.ENERGY, -this.eprod);
    }
  }
}
```

**Comment by kevinb9n** [comment]
I see that the new standard projects need this, but FYI the card example shown doesn't seem to have titanium as a cost, just an on-play instruction like Moss, so I assume it would be implemented like Moss. The difference matters to e.g. Manutech, who can play that card and Moss even with no titanium/plant resources on hand.

(I think the only card in canon that could arguably be described as having an additional *cost* beyond the MC cost is Sponsored Academies.)

**Comment by bafolts** [comment]
Using `Fees | number` should be fine if it makes sense. Checking whether `number` is used at runtime would have to be done withe `typeof val === 'number'`. Could `Fees` be used with `Helion` on some way? The `Helion` card has been an annoyance from the beginning as one always has to remember that heat can be used. I would assume with this `Fees` class this logic could somehow be contained there. The `Fees` could help with cards but how would it help with standard projects? Today the standard projects are mostly written within `Player` or `Game`. Eventually we should move these to a `standardProjects` namespace and similarly to cards we could then write each standard project with a `cost`.

**Comment by bafolts** [comment]
Instead of using `Fees | number` could also consider being BOLD and only using `Fees`. That would require updating each card though. For the situation where only mega credits are needed a `Fees.credits(3)` could be used.

**Comment by kberg** [comment]
> Instead of using `Fees | number` could also consider being BOLD and only using `Fees`.

That's up to someone else six months from now. Does not seem worth it here.

**Comment by Lynesth** [comment]
I don't think this is necessary.
There's only 9 cards where it matters to be careful because they need to remove a resource that they can pay with.
They should probably just be handled like Stratospheric Bird is when you have Dirigibles, simply in their `canPlay`
You'll also need to make sure the player cannot spend those when selecting how to pay for the card (like StratosBirds).

And it's going the opposite direction I was with an upcoming PR (maybe that's the real reason haha).

**Comment by kberg** [comment]
Perhaps. But I also don't think it will make a huge change to the code,
hence even though it adds an overhead, if it's localized and not terribly
large, it might be an acceptable addition to the whole game's structure. I
counted 33 cards that have a bonus cost, not to mention the standard
projects. Of course, these cards don't have the steel in the card cost, but
it's basically a prerequisite for canPlay. However, I am in touch with the
author, so I'll ask what their take is on how the card is meant to be
played (eg should we treat it like a card cost)

I peeked at your PR, @lynesth but didn't fully understand it. It looks
ambitious, let's chat later.

>

**Comment by kevinb9n** [comment]
> Instead of using `Fees | number` could also consider being BOLD and only using `Fees`. That would require updating each card though. For the situation where only mega credits are needed a `Fees.credits(3)` could be used.

I actually wouldn't recommend this, because the number is "special"; it's a number that (depending on the card's tags) can be fulfilled by some combination of megacredits and other resources. If a card has an additional "lose 3 money" effect in the body, that has to be pure money. (Leaving Helion aside, the only special case of having *blanket* permission to use something else as money.)

I haven't been able to tell if my comment above was seen. A "cost" and a "remove your own resources" on-play instruction are different things and even happen at different times. My understanding, though I am always trying to refine it, is that *after* a cost is fully paid, the card's effects "turn on", then the union of all on-play instructions on the card and all when-play effects triggered by the card or its tags go into one big pool of instructions to be carried out in whatever order is most favorable to the player.

I could have a bug in that explanation, but the point is that these are two very different things. And the card shown above is not ambiguous, it's made in the image of Moss.

**Comment by Lynesth** [comment]
> I peeked at your PR, @Lynesth but didn't fully understand it. It looks ambitious, let's chat later.
Sure thing.

**Comment by sienmich** [comment]
Maybe standard projects should be implemented as cards? They would have their `play`, `canPlay` and `cost`. And choosing standard project from cards instead of text list would be better for new players. And it would help to implement those moon projects. What do you think?

**Comment by kberg** [comment]
Good thought, but I think it wouldn't have quite the effect -- standard projects seem easy enough to manage as the question as to whether they can pay are hard-coded, whereas card requirements are managed in one place.

**Comment by Lynesth** [comment]
@kberg There's only 9 cards you need to manage in the Moon expansion. Those are the ones that can use Steel to pay and need to spend 1 steel as an effect and the same thing regarding titanium.

I think the "easiest" way to do it without modifying current code would be to do something like this in the `canPlay` of the card:
```ts
// Example using Mare Seneritatis Mine

public canPlay(player: Player, game: Game) {
  if (player.steel < 1 || player.titanium < 2) {
    return false;
  }
  // Need to spend 1 steel as an effect, but can also pay with steel
  const canPay = (player.steel - 1) * player.getSteelValue() + player.megaCredits + (player.canUseHeatAsMegaCredits ? player.heat : 0) >= player.getCardCost(game, this);
  return canPay;
}
```

**Comment by kberg** [comment]
@Lynesth you're right about the cards, I see your point. And I was thinking about Stormcraft Incorporated:

![image](https://user-images.githubusercontent.com/413481/103112913-2c3f9c80-4626-11eb-8060-feb02b69b465.png)

(Which I just learned about reading #2177.) Now of course a player can't be both Helion and Stormcraft. So that means I'm just digresseing at the moment. But IMO it is a mistake to have each card deal with this peculiarity.

I would accept, though, having one special implementation of canPay for calculating these 9 cards. That's fine.

This is further complicated, sadly -- by actually collecting the fees. A player paying for one of those cards *must* set aside 1 steel before paying otherwise the SelectHowToPay will allow a player to spend all their steel before playing the card. Any thoughts?

**Comment by Lynesth** [comment]
At the moment (for Stratospheric Birds since it's the only one in that case) that's checked in `player.checkHowToPayAndPlayCard()`.
I agree that it's a bit "meh" to do it like this but:
1 - It would be only a few lines of code
2 - It's easier than having to deal with it on the front end side.

So it would look like this (very quick example, but you get the idea):
```ts
  public checkHowToPayAndPlayCard(selectedCard: IProjectCard, howToPay: HowToPay, game: Game) {
    // ....
    if (canUseSteel && howToPay.steel > 0) {
      if (howToPay.steel > this.steel) {
        throw new Error('Do not have enough steel');
      }
      if (this.isCorporation(CardName.MANUTECH)) {
        if (selectedCard.name === CardName.MARE_SENERITATIS_MINE && howToPay.steel === this.steel) {
          throw new Error('You cannot spend all your steel to pay for ' + selectedCard.name);
        }
      }
      totalToPay += howToPay.steel * this.steelValue;
    }
    // ....
  }
```

**Comment by nwai90** [comment]
After thinking about this for some time I would agree with @Lynesth .

The main structural issue with the `Fees` approach as I see it is that we are conflating `canAfford` logic with `canPlay` logic. Imo the latter should strictly be about the player being able to afford the card's absolute MC cost, which is a property of a project card. Conflating these also raises the question of why energy production decreases are included in `Fees` but not other types of production decreases.

Additional requirements (e.g. decrease your energy production 1 step, a player has removed another player's plants, you have steel/titanium production) are currently checked in `canPlay` which I believe is better for separation of concerns. It should be feasible to check for the existence of X steel/titanium in `canPlay` and add the appropriate logic to ensure that X units are "reserved" after paying for the card's cost.

**Comment by kberg** [comment]
This is helpful, thank you. For the time being I'm going to keep using Fees
in Moon cards, but internally only, and side-step the additional
payment issues, just to focus on completing a workable solution that might
put some careless players in a no-action scenario (or accidentally given
them a negative steel count) because the sooner this gets into testers
hands the better.

In the meantime, I'll keep this bug open.

>

**Comment by kberg** [comment]
@Lynesth this is definitely going to be more compliciated and prevalent across all the cards.

![image](https://user-images.githubusercontent.com/413481/103465490-ea8bb180-4d09-11eb-925e-342d22720be4.png)

**Comment by Lynesth** [comment]
Still doesn't seem to be much of an issue to me. The only cards that make you lose titanium (or steel for that matter) when played are from the Moon expansion, so that corp does not influence the rest of the cards.

Just make a `MoonHelper` method that checks if the player can pay for the card and still have enough resource to "pay" the extra ti/steel from the card effects by passing it 4 arguments: `player` (to check if the player is **LTF**, **Manutech**, etc or has **L.T.F. Privileges** down), `card` (to get the real card cost), `extraSteel` and `extraTitanium` (to know how much you're going to lose from the card's effects).

Call it in all related Moon cards' `canPlay` and you're good.

---

/rant
But in the end, that's the reason I'm not fond of most fan made expansions. They more than often break the original design of the game. You don't lose resources from playing appart from like, 6 exceptions (3 cards make you lose plants, 2 make you lose 1 floater and 1 make you lose heat). And you surely don't lose resources that can usually be used to pay for certain cards. Also, I think that giving a corp the power to use titanium to pay for everything still goes against that idea. It woul dhave been plants or energy I probably wouldn't say the same because it would be in line with Helion, making use of resources not used to pay with, to pay with.

And in the end it makes us modify core methods/functions that start to look more and more like spaghetti code, to incorporate all those edge cases. Maybe we should revise the app architecture to somehow allow expansions to be written independantly and have the ability to just plug them in the core of the app when selected, where they would provide their own functionalities, using listeners or something. I don't know, I haven't really thought about it but I'm really starting to.
Anyway...

/rantoff.

**Comment by kberg** [comment]
Maybe it's that simple. I continue to avoid the problem (which is fine - I'd rather solve it en masse.)

It's a fair rant. As far as the expansion itself goes, of course that's a matter of taste. I think as a group, sticking to the more popular fan expansions of the forum, or projects that the devs themselves care about (Political Agendas here is a great example) is a reasonable guide.

But I think your concern about spaghetti code, while fair, is something to consider when maintaining the codebase. This may be hubris (no offense to our fine community member Hubris)  but I think the work I did to bring Ares into the game simultaneously cleaned up quite a lot of areas that were spaghetti code. So, there's an opportunity to force the codebase into a better architected solution that will take these expansions.

The fact that I had SO LITTLE work to do just to make the majority of this expansion work is a testament to the past work done to generalize so many previously hard-coded things.

**Comment by bafolts** [comment]
I worked with someone at one point who updated the early wikipedia page claiming they were the inventor of spaghetti code. Having worked with someone who at least according to wikipedia invented spaghetti code I don't think that is what we have here. More often than not the problem we run into is similar to Helion. It has been here since the first cards. Very unique cards are cumbersome to work into some system and it is impossible to see what is coming up as needed in upcoming cards. Cards are not bound by any constraints so we will never be able to have some system supporting them all in some system.

I like what the AresHandler did in regards where it at least contained it's logic. What I think we should put in place as a design principal is that the base cards always get precedence, anything fan made is orchestrated through these "Handlers". Wherever we now have AresHandler we could put in some system to ask if _any_ Handler needs to do something at some point in the code and then let the Handlers modify `Player` or `Game` external or the core logic. This should at least move most of this logic into `MoonHandler`, `AresHandler`, and `TurmoilHandler`. In terms of application layering any functionality included in the base game would get preferential access to `Player` and `Game`. For each `Handler` we could come up with a system similar to how ares stores it's data on player through `aresData`. We could try to make this more generic as `player.handlers[Handlers.ARES].someState`. I don't think we can avoid calls everywhere to `Handler.canWePayForThis()` but this would at least put in place where we track state for each Handler and where we store one off functions for each handler. In regards to naming it probably makes sense to use `Expansion` for the naming. Then we would have `MoonExpansion`, `AresExpansion` and `TurmoilExpansion`.

**Comment by kberg** [comment]
Here's my current attempt. Haven't tested, just wrote. https://github.com/kberg/terraforming-mars/commit/f58e2c33981e976b9ef72386c16c1b62e68d7405

**Comment by kberg** [comment]
This is submitted.
