### ISSUE TITLE
Card not found in tests

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#2215]
@bafolts There's 2 vuejs tests that are not able to find cards somehow. It's been like that from the beginning as far as I can tell, and tests are still passing properly but I realized the issue when I added a warning if the card couldn't be retrieved in #2208.

![firefox_2020-12-29_20-36-18](https://user-images.githubusercontent.com/5318258/103274324-84571400-4a15-11eb-81ff-af2bada4e08f.png)

**Comment by Lynesth** [comment]
Ok so we have 2 culprits, both in `src/components/card/Card.ts`.
The first one is its `getCard` method that searches through project cards, then corps, then standard projects.
Second one is the `getCardExpansionByName` function that searches through each type of cards of each manifests (that's at most 36 searches).

**Comment by Lynesth** [comment]
Ok so, last post from me on this matter.
- I removed the warning for now, as it really slows down browsers when there's a lot of cards.
- The component calls `getCard` way too many times, iterating over all cards again and again while this should be done once and saved (when mounted for example ?)
- I'm not sure how to "fix" the warning thing. How I see it (without changing too many things), it's either we simply keep it removed or we make sure that each call to `Deck.findByName` from the component searches through all cards at once.

**Comment by bafolts** [comment]
In regards to the performance, I am going to assume without having measured it that when you take an action on the UI and it seems to respond slowly this is due to us traversing through the countless cards looking for your card. We have plentiful cards now that iterating through each card would be noticeable if you were doing it often. Since the `cardName` is a unique key we should be able to use a map to find the card without needing to iterate through every card. This change should help us on both the server and the client. I will change this to use a `Map` with card name as key for `Deck` to make these look-ups far less CPU intensive.

In regards to the warning. I do think it was helpful as it spotted this area for improvement and it wasn't an error. Searching through every deck at once will address the issue. I will put up a PR with these two changes. It should go a long way for CPU improvement. I will turn the warning back on with the change.
