### ISSUE TITLE
Show cost of all standard projects

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#2221]
I saw this was alluded to in #2192 discussion, but I wanted to highlight it specifically. There is no listing on the UI for costs of standard projects I can't afford at a given moment.

Scenario:
If I want to sell patents to buy a standard project that I cannot currently afford, I don't see a reference to confirm its cost (and thus how many cards I need to assess the sale of), since the projects above my current MC total are not displayed. Can they be shown but greyed out? Or add a reference around the game board for various costs?

I'm constantly second guessing myself on if a greenery costs 22 or 23 MC.

**Comment by kevinb9n** [comment]
As a *general* rule I think dimming is "always" better than hiding, and made a short speech about it here:
https://github.com/bafolts/terraforming-mars/issues/2175#issuecomment-750410475
(a VERY short speech by my standards :-))
In this case, keeping them all there also lets you play a little bit more from muscle-memory. A very very small point.

By default I would keep everything in (even Aquifer after all the oceans are placed, since the new "warnings" system should address that?).

There can always be specific reasons that override a general rule though.

**Comment by sienmich** [comment]
Yep, I still remember that one :)
Will work on this probably soon, thanks for reporting
