### ISSUE TITLE
Selling patents requires too many clicks

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2232]
With new Standard projects in order to sell a patent we need to click 5 times (sry for that):
- Standard projects
- Sell patents
- Confirm
- Card
- Sell

This should be reduced to 1 (or maybe 2 with one confirm).

There was an issue about reworking all player input with popup options. I can't find it right now (@kevinb9n? help :smile: ). I liked it very much.
I think it's time to merge `Play project card` and `Cards in hand` into one thing and add there some shortcut to sell one patent.

I propose sth like this (the trash bin should be much smaller to reduce unintentional clicking):
![Screenshot from 2020-12-30 15-38-56](https://user-images.githubusercontent.com/19472604/103358286-8e305400-4ab5-11eb-8908-1bcd170c6b5a.png)

**Comment by kevinb9n** [comment]
I must agree that selling patents has been a little annoying now. You also can't cancel out of it once you start, like you could.

I was gonna ask if you'd consider the *temporary* move of just putting Sell Patents (and only that) back to the way it was.
(It seems like a total accident that the game even considers it to BE a standard project at all, and nothing actually depends on that.)

As for the broader idea I'd like to hear @aragos's thoughts. (the issue you were looking for was hard to find because it was moved out of issues to discussions - it's #2121)

**Comment by vsrisuknimit** [comment]
> ![Screenshot from 2020-12-30 15-38-56](https://user-images.githubusercontent.com/19472604/103358286-8e305400-4ab5-11eb-8908-1bcd170c6b5a.png)

That would cause so many misclicks.

**Comment by vsrisuknimit** [comment]
Any way we could reverse to what we had before for this selling card action and try the experimental feature on a different branch. The current card selling implementation has negative impact on the game play on the main server.

**Comment by sienmich** [comment]
I agree. Unfortunately I won't be having computer access this week. Can sb else return it? In following weeks I'm planning to work on some better version of this issue

**Comment by bafolts** [comment]
I can move "Sell Patents" back to a separate action.

**Comment by sienmich** [comment]
> I can move "Sell Patents" back to a separate action.

Thanks!

**Comment by nwai90** [comment]
@sienmich Having "Sell Patents" as a separate action should suffice. The main issue I saw with the above mockup is that it would force patents to be sold one by one. I think it is different from "Play card" in that you can only ever play one card during an action, whereas you could sell one or multiple patents in a single action as you deemed fit. The previous approach also avoids adding an extra confirmation step for each sale.
