### ISSUE TITLE
hide the "active" and "next" labels during drafting?

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2260]
It's confused me many a time. Wait, why am I active?
Just a small thing though.

**Comment by ap3h3ad** [comment]
Instead of just hiding those labels it would actually be a real improvement to use those (or other) labels to show which player has yet to draft. Since this is clearly stated in the players attribute _needsToDraft_ this shouldn't bee much work.

**Comment by chosta** [comment]
@kevinb9n because it's your move to make. Next was added because of the fact that your interface is always at the bottome and for players not used to that, it can be confusing to follow the flow. Imagine seeing `active` and not knowing who the next player is. Is it the interface at the top or at the bottom? So this is merely a hint to learn how the turn order works and for experienced players it's not very useful but since it's a very subtle element, I think it should stay.

@ap3h3ad this is a consideration for the next UI upgrade.

**Comment by chosta** [comment]
> I am not sure what they are supposed to mean while we are doing a simultaneous action

You are correct, they shouldn't be visible when drafting. Let's see how the new UI comes along. We can change / remove them
