### ISSUE TITLE
consistency of VP text on cards

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2325]
I think the separation of vp-text from immediate-instruction text on the cards is a good move. I have some questions and review comments:

Main thing: is it possible to move the VP text to the bottom of the card to the left of the VP symbol? I feel like to new players the cards are a confusing jumble of different kinds of information and any kind of structuring like this would (I think) help.

To conserve space, perhaps the wording could be standardized on the compact form, using Ants as an example: "1 vp per 2 microbes here." When the resource is described in two words like "preservation resource" then it can just say "resource". (In general I think we could always use "here" in place of "to/from this card".)

Jovian Lanterns is missing that "here" part.

Commercial District: "place this tile" doesn't belong in the vp text?

These four cards aren't yet separating the vp text from the immediate text. If any are intentional for space reasons I am wondering if we have other solutions that are possible, because I think the separation seems good for accessibility.

Asteroid Deflection System
Asteroid Hollowing
Birds
Decomposers

Lastly Self-Rep Robots seems to be using vp-text style for its effect. Is that, again, just because it was the only way to make it fit?

@chosta

**Comment by chosta** [comment]
There are two ways we can approach this:
1) Try to be as close as possible to the original. This would not be possible for all of the cards because the vp bold text was a side effect to a card that couldn't mimic the original.
2) Keep the vp bold text as it is and try to have it as consistant as possible. Note: I've tried to move the text to the left of the VP but it does not look well in 100% of the cases. Sometimes description needs to be tucked in there. Basically, I've managed to find space with this solution and there were some side effects but at the end I think it's a reasonable look. Note 2: Self-replicating just looked better with bold text, the same as pets (Pets I took from Simon's design).
