### ISSUE TITLE
Cards UI: showing resources on cards

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2332]
This is about the gray resource doodad in the lower left:

<img width=300 src=https://user-images.githubusercontent.com/934551/104132248-d6126f00-5330-11eb-9757-d84a11a08282.png>

1. If we could solve how to make it not overwrite text like that (not to mention the expansion icon), then I think it would be very helpful to have this element *always* displayed for that card in all circumstances. While in hand or in draft, the number would presumably just be a blank "__" instead. This would improve on an existing weakness of the printed cards by making it quick and easy to distinguish which cards can be resource-holders.

2. Any reason it should not show "2 &lt;animal-icon>" instead? This would look nicer and when I'm deciding whether to draft StratoBirds or not I could very quickly spot whether I already have a floater-holding card. Also note that on a card like Titan Shuttles "RES" means one thing while it's in play and a different thing while it's on Self-Rep Robots, so the icon would be a little more specific.

**Comment by nwai90** [comment]
Agree that (1) is ideal if we can find a way to always display it, so that we can do away with the hover effect. Regarding (2) I think the `RES:` in `RES: X` is necessary for context as it is very unintuitive to just display a number.

**Comment by kevinb9n** [comment]
UGH, my comment is completely confusing. I always forget that when I write 'Any reason it should not show "2 &lt;resource-icon&gt;" instead?' that github will eat the part in angle brackets as if it's html. So, that's what it was supposed to say. It should certainly not say just 2.

**Comment by kevinb9n** [comment]
@nwai90 hey, would like to know if the report makes more sense now that I corrected the html :-)

**Comment by nwai90** [comment]
@kevinb9n I'm not sure it is better than showing `RES: 2` here as we would be displaying two resource icons in the bottom section in that case. One for tracking number of resources and one for indicating scoring formula (e.g. 1 / animal) is likely a visual overload. Tagging @ssimeonoff @chosta for opinions

**Comment by ssimeonoff** [comment]
When I was editing the previous counter (a floating yellow box) I had 2 ideas:
1. Make is slick so it blends in with the card (visuals over functionality) 
2. Place it over the card somewhere it doesn't cover other elements/text, ignoring how it looks (functionality over visuals) 

For 2. I could think of only for two options, because the counting should be without the card's borders:
a - right next to the price (on my cards-list I show the card number/id there, but here it is empty)
b - right next to the requirements box (usually this area is empty)

a. looks really weird, showing 2 numbers right next to each other (counting the price).
b. can look something like that: 
![1](https://user-images.githubusercontent.com/6917565/105472216-efee7300-5c9b-11eb-8e8b-ec503e45ef76.png)

The counter doesn't have the text "res",  it is elevated and squarish, hopefully to make it looks a bit similar to the cubes you put over the cards in the normal game and less similar to the other card's visual elements.

**Comment by kevinb9n** [comment]
Note that *just* fixing the part where once the card IS played, we always see the "RES:" display in every context (like when clicking a card in the log) would be big help. (This was just raised in discord.)

**Comment by kevinb9n** [comment]
I guess I'll add more examples: in "select a robot-linked card to double the resources of", it'd be super handy to see the current resource amounts right there.
