### ISSUE TITLE
Cards available for purchase for second time in the same generation after undoing first move in generation

### ISSUE THREAD

**Issue by trzycztery** [bafolts/terraforming-mars#2536]
After first player of gen. 9 (blue) has undone his move (Artifical Lake placement) and refreshing page, he was presented with cards purchasing view again. Those were new cards, the old ones from normal card purchase were present in hand and paid 3 MC/card for. I refreshed my page too at the same time. All players were presented new cards at that point, I am not sure if all players had refreshed page. 
Violet player (me) had purchased Capital and some other card from the first set, and Release of inert gas from the second set - confirming that it was indeed working as second card purchase. The card was fully functional, as I have played it later in game.
Other players did not purchase any cards from the second set.

Game ID: 36e4c4ebf36e
Violet player view: adf9de176484
Blue player view: 1d0de8e58871

**Comment by bafolts** [comment]
All of these undo bugs we may want to put into one bucket. I am going to guess they are due to one of two things.

When we serialize a game we don't serialize the deferred actions. Any critical state to the game in the deferred actions will be lost.

https://github.com/bafolts/terraforming-mars/blob/main/src/Game.ts#L394

When we serialize a game we also don't store the "waiting for". During an undo we may also lose any critical state being tracked in the waiting for.

https://github.com/bafolts/terraforming-mars/blob/main/src/Player.ts#L74

The deferred actions should be relatively straight forward to serialize. The `waitingForCb` property is a function that we can't serialize. A larger refactor will be needed to change the type of `waitingForCb` to something that we can serialize.

Once both of these changes are made all of the issues with undo should go away.

**Comment by Lynesth** [comment]
This is a new issue that is mostly related to one last change I made, I'll check.
The game is saved at the beginning of a player's action, after all deferred actions have been resolved so serializing them shouldn't make any difference (unless you start wanting to save between each deferred action that prompts the player).
