### ISSUE TITLE
RFC: Modularize deck creation by generating CardNames.ts/CommunityCardManifest.ts during build?

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#2732]
In my fork, my friends and I have been trying out new card ideas. For example:
![tfm-new-cards-2021-02-07](https://user-images.githubusercontent.com/58322/107706493-40db0100-6c75-11eb-885f-ea3597e9ff22.png)
Maybe you think these cards are crimes against humanity, and maybe you love them and want them in your game -- I imagine there are diverse opinions. But this sort of experimentation and play-testing is also one of the ways to make the game fun.  It would be great to have a more portable way for people to engage in this sort of experimentation.  Many interesting cards can be made using the existing building blocks in the current implementation without changing any of the core game logic or definitions. However. there are several bottlenecks that prevent this from happening:
- Cards must be registered in CardNames
- Cards must be added to a card manifest
- The Card Loader must know about the manifest
- Game creation must allow selecting the manifest

A first step to addressing these bottlenecks would be to automatically generate manifests for cards. Initially, maybe this is only necessary for the community cards (and anything custom and fan-made can live there). For the community directory, we could express the card list as a plain text file (consisting of name, path, and factory). Then a prebuild script (like make_static_json) could generate both the card manifests and append these card names into CardNames.  Someone could update custom cards by simply copying the appropriate card TS into their community directory and adding a line to the plain text list used to build the manifest. 

A more ambitious version of this idea would be to define the metadata in the card definition, have a script that auto-generates all manifests based on the directory they appear in.  Have the card loader know about all these auto-generated manifests, and the game creation dialog could have a sub-menu showing a dynamic set of card manifests.  What would be even better, is  replacing the exclude options in the game creation page with a card picker to include/exclude certain cards from the card list.

If a few people think this is a good idea, I might muck around with the simpler version. It's overkill if I'm just doing it for my own group, though.

**Comment by kberg** [comment]
Well, you can get most of what you want by adding cards to the Community
Card Manifest, which reduces the thing.

I agree the CardNames enum is a bit weird, but I'd be careful there.

Adding a new manifest is even more work -- you need to update the
CreateGameForm.

>

**Comment by puuj** [comment]
Yeah, my initial plan would be to use the Community Card infrastructure already in place. The main issue is that manipulating the list of community cards is fairly laborious. The ideal would be someone could just copy a card .TS into that directory and everything would magically work.

Can you expand a bit on the cautionary note on the CardName enum? What would you be most worried about? 

And, most importantly, if I build this do you think you (or others) would use it? For example, would this have helped you develop Moon stuff or is making changes to the manifest and card name files second nature.

> 
> Well, you can get most of what you want by adding cards to the Community Card Manifest, which reduces the thing. I agree the CardNames enum is a bit weird, but I'd be careful there. Adding a new manifest is even more work -- you need to update the CreateGameForm.
> […](#)

**Comment by kberg** [comment]
So I've thought a bit about this, and by and large I don't think this is an approach worth taking. I am not the arbiter of choice on this team, but I will share my perspective.

Not everything should be inflexlble, otherwise you can't make reasonable changes to a system without severe cost. Not everything should be flexible, because otherwise you lose the ability to comprehend the most common use cases. And so for every change that increases flexibility, you have to ask: what is being made easier that couldn't have been made easier before? And is that worthwhile?

In this case, what's being made easier? Adding a new manifest. Well, how often should someone be adding a manifest? Not very often. They're there for large and coarse separations, particularly I introduced them because card registration was an enormous bunch of code, used in several places. Manifests addressed this nicely.

But how often does someone need to add a new manifest? Well, when someone adds an expansion. That's the dimension on which manifests usually expand (at least at this point.) The Community Manifest is a bit like the bucket of individual fan ideas that aren't a full expansion, and is the exception to the rule.

Someone might want to add a manifest to represent cards they use locally. Which is your use case. It's not trivial to add a new manifest. Nor does it need to be.

is it worthwhile commoditizing manifests? I just don't see it. You can solve your problem another way: by creating just one manifest for your experiments - ExperimentManifest. Or use the Community manifest. Or we create an ExperimentManifest in the main repo. But I would only accept that if the Experiment manifest contained a comment at the very top saying "This manifest is _manifestly_ (ha ha) reserved for local forks to play with. You will never see this manifest in use in the demo repo."

Could the CardName enum be dynamically created? Yes, possibly. But I would be very careful there, and consider that a separate effort, because the wrong thing could make an existing game not load. That's the use case I'm nervous about, by the way. And an experimental manifest where cards come and go freely means someone can add a card name, remove it, and someone else itnroduces the same card name later (either through an upstream repo, for instance.) I'm not saying these are unsolveable, I'm saying that's not a problem I'm ready to tackle as a reviewer or maintainer.

**Comment by puuj** [comment]
Thanks for the very thoughtful reply. 
I can see how people dynamically changing the cards would screw up serialized games, so that makes sense.
My main use case was someone who is running a server but does not feel comfortable updating several files. If they could just copy promising cards from several sources into a directory and get those as options, it would make fan-made cards more accessible for all.  The other benefit is that experimentation would not require changes to files in Git since those updates could be generated and abandoned with no risk, and we can .gitignore the experimentation directory.

Probably my estimate of how many people are excited about this is too high, so I can just keep doing this as a one-off.

**Comment by kberg** [comment]
Thanks for understanding! I look forward to your card experiments.
