### ISSUE TITLE
Unexpected server response

### ISSUE THREAD

**Issue by ChrisTheCat** [bafolts/terraforming-mars#2808]
Playing async games on the demo server at herokuapp.org, I quite often get these pop up errors that steal focus from the active tab. I'm leaving the game open in a background tab on Firefox on MacOS.

<img width="261" alt="Screen Shot 2021-02-20 at 8 47 57 AM" src="https://user-images.githubusercontent.com/8732435/108602725-66909600-7358-11eb-9c71-f9b8298d1e12.png">

**Comment by vsrisuknimit** [comment]
@ChrisTheCat  This warning usually happens when the server is down, for a period of time or temporarily. The server is updated daily around 13:00 UTC.

As mentioned in the main repo page, the demo server is not great for async games. You should consider hosting your own server for async games. Check https://github.com/bafolts/terraforming-mars#-i-want-to-run-a-copy-of-the-server-locally

**Comment by bafolts** [comment]
I will use this opportunity to improve this situation. I first put in this `alert` on an error response in very early development days. Even on the terraforming-mars.herokuapp.com it is stable enough that if you are waiting for your turn there is no reason for alarm and we shouldn't show these alerts to the user. I will change this situation so that on error we log the error and try again. If you are playing an async game you are most likely waiting for your turn and you should eventually get a successful response. During reboots then users waiting to take their turn wont notice. The only players who would notice would be the player waiting to take their turn.

**Comment by bafolts** [comment]
It is interesting. I reboot around 8:00AM MST. Recently the heroku dyno has started doing this for me with a label of "daily restart". I don't know if someone with heroku access enabled this. Today the automated daily restart happened 20-30 minutes before I manually pushed out a new version. So around the time this bug was filed the error popup would have been seen twice as often as a usual day. In both situations a player waiting to take their turn shouldn't have to see the error. Only the player actively trying to modify the game state should be alerted so they can take their move again.
