### ISSUE TITLE
Draft order is displayed wrongly

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#281]
Hi,

one of my regular opponents discovered the following:

When you have to decide which cards you draft to the next person the displayed player is not the person to which you actually deal the cards. This can be tested in a 3 person game (at least it occured in a 3 player game) just with monitoring to which player you draft the cards according to the displayed text and which player actually gets them.

Also we noticed that the draft order switches between clockwise and counter-clockwise (at least according to the displayed player). Is this intentional? We could not find any information about this in the official rules.

Greetings!

**Comment by K-Hartmann** [comment]
Hi.
As an addition, i personally prefere the draft order to be opposing to the play order. That way you have more or less direct interaction with both your neighbours, and a bit of control wich cards to give to the player who would snatch away awards and milestones just before you.
Just a thought, since as far as I know the draft order is not specified in the rules.

**Comment by dabewi** [comment]
Maybe it's an option to make the draft order configurable per game.

**Comment by alrusdi** [comment]
Currently draft order is changing each generation. It was my suggestion to do it like this. Because it compensates the situation when weak player feeds only one player with good cards.

I will check if draft order is displayed correctly.

**Comment by vincentneko** [comment]
Draft order is specified in rulebook:

https://www.fryxgames.se/TerraformingMars/TMRULESFINAL.pdf

Drafting is not used during the first generation
since the first Research phase is skipped (see setup). Cards
are passed clockwise during even-numbered generations
and counter-clockwise during odd-numbered generations.

I confirm players are not receiving the cards they should have, will try to correct this.

**Comment by alrusdi** [comment]
@vincentneko ok, do it. We need more auto test on this feature. I can help you with them

**Comment by alrusdi** [comment]
Now everything should work fine. Thanks to @vincentneko
