### ISSUE TITLE
Bug: json upload does not allow player count change to be higher (but lower is allowed)

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3061]
![image](https://user-images.githubusercontent.com/14239220/112888654-a27af180-90a2-11eb-993b-1e032810950e.png)

See JSON file here: https://discord.com/channels/737945098695999559/742721510376210583/826172700262531133

![image](https://user-images.githubusercontent.com/14239220/112888974-09000f80-90a3-11eb-9ace-2a65f6e3d93e.png)

![image](https://user-images.githubusercontent.com/14239220/112889003-12897780-90a3-11eb-879e-783868a4c005.png)

@alrusdi ?

**Comment by bafolts** [comment]
This issue is [here](https://github.com/bafolts/terraforming-mars/blob/main/src/components/CreateGameForm.ts#L191). The `players` array on `this.$data` is set to the array with only 3 items. To fix this we should set the properties based on the index and not override `this.$data.players` completely.
