### ISSUE TITLE
Game lock

### ISSUE THREAD

**Issue by DERTAZ** [bafolts/terraforming-mars#3167]
The bug that occurs when trying to build a tile, even though it cannot be placed on the board, has still not been fixed.

https://terraforming-mars.herokuapp.com/player?id=p75942f4fa403#colonies

I chose to set up a SCIENTIFIC FACILITY, I did not notice that the place is already occupied, the game let me go, but it turned out that the only place possible was the endangered place that requires a fee. I do not have the necessary amount. The game is stuck and you cannot give up a move, or go back or skip.

**Comment by bafolts** [comment]
Thank you for providing game link. I can pull down the state of the game to help with recreating this.

**Comment by DERTAZ** [comment]
so you can go back the turn?

**Comment by bafolts** [comment]
Nothing can go back the turn unless the server were restarted. When the server restarts tomorrow morning it will revert to the last place the game was saved and that may fix it. I will pull down the state of the game so that when this bug is fixed this wont happen again in the future.

**Comment by bafolts** [comment]
This bug happened with the `Research Outpost` project card. The mild erosion tile shouldn't be available since the player doesn't have 8 mega credits.

![image](https://user-images.githubusercontent.com/2707843/115162241-a4abec80-a05f-11eb-8486-67779bb904c7.png)

**Comment by kberg** [comment]
This is a well-known issue that we have discussed solving a few ways. I'm
very sorry about this one because I don't have a simple solution, yet.

>

**Comment by kberg** [comment]
I wonder if, in the meantime, we could address this in this way: add an
option where, when a player must place a tile but cannot, they may press
it, "Do not add tile, requests approval from opponents"

Complicated, but achievable.

**Comment by bafolts** [comment]
I was working on a fix to this situation. When calling to the `getAvailableSpacesOnLand` function of a `Board` was planning on adding a check that the player can afford to place the tile. This involved refactoring the static function `assertCanPay` of the `AresHandler` class to return a `boolean` if the player can afford to place the tile. At that point the situation in the screenshot shouldn't happen as the space wouldn't be included with `getAvailableSpacesOnLand`. Am I missing a side effect with this solution? The user in this situation wanted to add a tile if they could so included an option to "Do not add tile" seems like we would be working around this bug.

**Comment by kberg** [comment]
If the hazard is next to the ocean or any space that grants adjacency
bonuses, or heat, and any space that costs extra MC, then those add into
the equation.

**Comment by bafolts** [comment]
I plan to change this to use the equation we have in place for now. It wont prevent every bug but it should have prevented the bug here as there are no adjacent tiles. Since research outpost has to be placed on a tile with no adjacent tiles it should fix it for the research outpost project. Then when the equation is updated it wont impact research outpost but can solve more cases where this is happening.

@kberg to solve these situations that will be inevitable where someone finds a bug that ends up locking the game I am thinking we could add an administrator route that allows a game to go back to the last save point. We would remove the object from javascript memory and the game would be taken back as if a player had performed an undo. With this route I could have fixed this game yesterday on the server whereas I can't do anything besides restarting the server today. It would also help if this were to happen during a tournament. Someone who knew the server id could get that game back to a state where it worked. Thoughts?

**Comment by kberg** [comment]
Yeah, I'm suggesting something that doesn't need an admin.

I'm a little nervous about solving more cases as they come up, because
there will always be more cases. For instance: playing the card that makes
you place a tile on one of the volcanic spaces (Lava Flows.) If few enough
volcanic spaces remain available and all of them abut or have cost-based
spaces next to them, this further complicates the costs. In other words,
perhaps move much of the addTile computation elsewhere.

By the way, this doesn't *further *take into consideration that placing
over a hazard when Ares and Turmoil are both engaged, that the reds policy
TR bumps apply. (Something I've neglected to deal with for both Ares and
Moon, BTW.) This is why I'd like to consider something like
https://github.com/bafolts/terraforming-mars/pull/1864

Here's one more use case. I love Helion. If a player has Helion, and
Optimal Aerobreaking, and plays the Promo version of Deimos Down. This
player will have 3 more units of heat to consider when playing that card.

This is why I'd like to suggest for now, a solution that lets someone back
out and say "Whoops. I can't place a time, and I'll just have to forego it.
Anyone disagree?"

Sorry if this seems like a bit of a pile-on. I have a lot of thoughts about
this. :D

>

**Comment by bafolts** [comment]
#1864 is focusing on solution to this.
