### ISSUE TITLE
Global events trigger Mons Insurance payouts

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#3215]
The Mons Insurance corp effect states "When a player causes another player to decrease production or lose resources, pay 3M€ to the victim, or as much as possible." However Global Events that cause players to lose resources are also triggering Mons. Since global events are not "a player," one could argue this should not occur. Is this the expected behavior, and is there a reason for it?

**Comment by puuj** [comment]
Yup, this is a bug! Used to be this:
`    // Mons Insurance hook
    if (game !== undefined && amount < 0 && fromPlayer !== undefined && fromPlayer !== this) {
      this.resolveMonsInsurance();
    }`
After @kberg changed the production options to have a from: field it now looks like
` if (amount < 0 && options?.from !== undefined && options.from !== this) {`

I can change it to look the the Global Event code so,
`(options.from instanceof Player && options.from !== this)`

**Comment by kberg** [comment]
Ugh, sorry about that!

Your fix makes sense. If you do it, please add a test. Otherwise I'll fix
it in about an hour or so.

>

**Comment by bafolts** [comment]
Also while we are here instead of checking that `options.from !== this` I would recommend using `options.from.id !== this.id` and comparing the player id once we know that `options.from instanceof Player`.

`(options.from instanceof Player && options.from.id !== this.id)`

This check will avoid needing to have the same instance of `Player`.
