### ISSUE TITLE
Undo broke

### ISSUE THREAD

**Issue by ChrisTheCat** [bafolts/terraforming-mars#3263]
Two players in our game experienced this. When we chose undo, we got the following error, the action was not undone, and our turn was ended.

<img width="550" alt="Screen Shot 2021-05-07 at 3 18 07 PM" src="https://user-images.githubusercontent.com/8732435/117513987-bb02e500-af47-11eb-8a15-fe10607e6521.png">

**Comment by bafolts** [comment]
Was this game being played from `terraforming-mars.herokuapp.com`? If the undo operation fails it will be because of a database issue. Every other action of the game avoids needing to pull data from the database.

I think two things can be improved here:

1. Show the error message as to why the undo operation failed. This will allow us to see _what_ the error was.
2. Don't end the player's turn on this error. On this error the player should be allow to take another action or perhaps try to perform the undo operation again. The `terraforming-mars.herokuapp.com` is fairly reliable but isn't 100% reliable on the hobby basic plan. The undo operation would most likely work on a retry.
