### ISSUE TITLE
Implement some form of memory collector to free heap space.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#3300]
The heroku instance (terraforming-mars.herokuapp.com) is still quite popular. With more being logged to the game logs we are also logging more. This is causing the memory to climb again. Starting two days ago was the first day I have seen the heroku instance run out of memory and restart the dyno. This restarting of the dyno has proven risky. Last winter this would sometimes prevent the dyno from restarting and the host would become unreachable.

![image](https://user-images.githubusercontent.com/2707843/118826533-6b3deb00-b870-11eb-9114-0ce994e346f0.png)

One strategy which I think will be effective is running an interval. This interval will look for games in the `GameLoader` that have ended but we are storing in javascript memory. It would remove these from javascript memory. A player that is still using the instance could request the game. If the game were requested we would pull it from the database.

**Comment by kberg** [comment]
Not dissimilar to this; I'd still like to change the way a game is closed out. Rather than immediately delete all the intermediate entries for a game, store them for long enough to do triage. The reason that is simialr to this is that it's meant to execute something some time after a game has ended. The difference, though, is that an in-memory purge is much easier to do than a delayed database purge; I'll probably need to add something to the database. (Or perhaps the GameLoader will help out?) Anyway, something that simulates a cron in the web app ++
