### ISSUE TITLE
Better payment validation

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#359]
Check if payer trying to pay more than required and warn him before accepting payment

Sample situation:
You can overpay by mistake when more than one resource is available. 
a) With Stormcraft, have 5 heat and 2 floaters on the card. when paying you can select first the 2 floaters and then you start paying with heat - it won't stop at 4.
b) Have 2 Building card costing 8MC. Pay 2 Steel first then start paying with MC - it won't stop at 4.

**Comment by thenewjuniorexecutive** [comment]
Also - c) You can always select all of your Steel or Ti, even if that exceeds the price by more than a single resource's worth. Max amount on the spinner should be ceil ( cost / resource value).
d) Decreasing a steel/titanium payment amount always adds back a full resource. So if you have selected 4 steel & 0 MC for a 7 MC card, decreasing the amount of steel by 1 makes the payment 3 steel & 2 MC (instead of 3 & 1).

**Comment by bradwerth** [comment]
> d) Decreasing a steel/titanium payment amount always adds back a full resource. So if you have selected 4 steel & 0 MC for a 7 MC card, decreasing the amount of steel by 1 makes the payment 3 steel & 2 MC (instead of 3 & 1).

This part is fixed by #520 and fix-ups #529 and #547.

**Comment by nwai90** [comment]
Hi @alrusdi I will submit a PR for this to show a simple warning popup if player overpays for a card or card action.

**Comment by vincentneko** [comment]
With the last commit from @nwai90 I'm closing this issue.
@bradwerth @alrusdi @nwai90 thanks for your help on this topic.

**Comment by nwai90** [comment]
Thanks @vincentneko ! The UI is probably not the best right now since it uses the native browser confirm popup, but it's fully functional so this should give us opportunity to improve the display and styling in future
