### ISSUE TITLE
Better UI for actions block

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#360]
We need to:

1) Sort actions by popularity

2) Highlight actions to make them different from other page texts

3) Save button (which actually a button Confirm) should be displayed under the clicked action/card than needs to be confirmed (to avoid a lot of vertical scrolling)

**Comment by vincentneko** [comment]
Illustration of point 3 from Simon:

![actions](https://user-images.githubusercontent.com/56086992/76140111-54d6b580-6057-11ea-925b-2d90b28eace2.png)

**Comment by gomfunkel** [comment]
In my humble opinion it would be great to have larger buttons instead of small checkboxes for the available options. Especially on mobile devices it's sometimes hard to hit the option you want.

Regarding sorting by popularity: I don't think that's a good idea. The buttons/checkboxes should always be in the same place. Doing the stuff you want enters the muscle memory quickly so changing the sort order is not a good idea as far as I am concerned.

**Comment by rzulian** [comment]
I do agree with @gomfunkel . I wouldn't change the order of the actions, unless @alrusdi you are meaning to reorder it once and then keep it.
I would also suggest to stick "Pass" action on the bottom

**Comment by alrusdi** [comment]
yes, i mean to sort actions by popularity once an then keep it.

**Comment by gomfunkel** [comment]
@alrusdi If it's not about reordering the actions every time I withdraw my comment. Thank you for clarification.

**Comment by vincentneko** [comment]
I'm closing this one as many things have been done to improve the UI.
Thanks to @nwai90 for the improvements.
