### ISSUE TITLE
Turn should not end if one action was done

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#4]
As per the rule book :

You can choose to take 1 or 2 actions on your
turn. If you take no action at all (pass), you are out of
the round and may not take any anymore actions this
generation. When everyone has passed, the action phase
ends.

**Comment by bafolts** [comment]
This is how the logic should be in place. This may be an issue with the user interface where only actions you can take are displayed, otherwise only the pass option is displayed. This could be confusing and not obvious that there are no actions you can take, especially early in the game. Or this is a bug. Will investigate.

**Comment by vincentneko** [comment]
As long as I have some projects cards in hand, I can use the sell patent project.

**Comment by bafolts** [comment]
What actions do you take to recreate this issue? I don't usually play two player games and this issue isn't obvious in a one player game since you can take actions until you pass.

**Comment by vincentneko** [comment]
Create a 2 player game. Each player buys the 10 project cards. Each player use a sell patent action and sell one card, then pass. Game will move to generation 2.

**Comment by bafolts** [comment]
In the steps to reproduce you list that seems like what should happen. If both players pass then the game should move to the second generation. I did run into an issue with two players related to selling patents where after selling patents from player one the game assumed I had used up two actions when I only took one so there is a bug here somewhere. For some reason I put in the code to update the actions taken twice and I can't remember why it is there.

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L572

I can't always seem to get this to be a problem and will have to investigate further.

**Comment by bafolts** [comment]
Ah, I now see the problem here! If a player takes one action and then is done for that turn a separate action will be needed. I will add in an option besides "Pass" which is, "Done with this round" or some better name (suggestions welcome). This separate action will only be visible once a player has taken at least one action.

**Comment by bafolts** [comment]
There is no an option to end your turn as well as pass. Ending your turn will only end your turn for that round. The option is only available if you have taken one action.
