### ISSUE TITLE
Flooding can break solo game

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#481]
After placing the ocean from the card "Flooding" in solo play, prompted with options:
 "Select adjacent player to remove 4 mega credits from" and
"Don't remove mega credits from adjacent player"
The first option has a single blank radio button below it. Selecting this option and the blank button results in "Error sending input".

Switching to "Don't remove mega credits from adjacent player" then gives "Error sending input"

Refreshing the browser after this gets "Unexpected server response" and a blank screen

**Comment by bafolts** [comment]
Right now if we have any issue processing input and javascript has a runtime exception the game server process will crash. @vincentneko this is probably an opportunity where we could leverage an interrupt instead of the somewhat legacy returning of an option. I don't know if that would fix the bug but I don't see anything that stands out as an issue and the interrupt system is less prone to error.

**Comment by vincentneko** [comment]
This is the only place where an interrupt was no possible to put in place as there is a decision to be made. I will switch to interrupt logic for single player games.

**Comment by vincentneko** [comment]
Fixed and merged.
