### ISSUE TITLE
Mining guild get no bonus when placing ocean

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#6]
I have Mining guild corporation.
I do not get an increase in steel production if I place an ocean on a tile with steel or titanium placement bonus.

More info in this thread : https://boardgamegeek.com/thread/1634178/mining-guild

**Comment by bafolts** [comment]
I see the issue with this one. Since no one technically owns an ocean tile I don't associate a player with an ocean. The check to assign bonuses when a tile is placed makes sure the tile placed was by the player.

https://github.com/bafolts/terraforming-mars/blob/master/src/cards/corporation/MiningGuild.ts#L15
https://github.com/bafolts/terraforming-mars/blob/master/src/Game.ts#L593

I don't think there will be repercussions from either removing the player association after the tile bonus or just keeping track of which player placed the ocean tile.

**Comment by bafolts** [comment]
This should be resolved.
