### ISSUE TITLE
Reconsider when we deploy updates to the hosted heroku site.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#614]
Every time we do a commit to master a new version of the app gets deployed to the heroku site. If someone was in the middle of a game this interrupts their game. We should deploy at a certain time of day or come up with some other release strategy, or keep this in mind.

**Comment by Seerus** [comment]
Hello everyone!

I cloned your repository to myself and also launched it on heroku.com, so that in the middle of the game I would not encounter a deployment.
When playing a solo game (I haven’t tried others) if I take a break between moves of several hours, the error "Unexpected server response" may occur
Apparently, the point is not in deployments in the middle of the game :(

**Comment by hbofolts1** [comment]
The free heroku tier that is used puts the node process to sleep every half hour, but don't quote me on this. I will look into paying for the heroku that is used given everyone is stuck at home.

**Comment by Seerus** [comment]
Ahhh ... Got it, thanks

**Comment by bafolts** [comment]
I have upgraded the heroku account from the free level to hobby level. This should prevent the node process from sleeping every 30 minutes which was most likely causing both of the bugs reported since we really don't deploy that often. If we still get issues reported we can make a subsequent task to only deploy updates on given days. I am guessing some of the recent interest in this project correlates with the virus spreading around the globe. Assuming no one pushes a change to data mine from the heroku process I will pay to host this unless traffic usages becomes way too high. With the hobby account I can now see the usage so I can get some idea for how often the site is being used.
