### ISSUE TITLE
Global event triggers dialog with no instructions

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#688]
After removing an ocean when resolving the global event "Dry Deserts", the following dialog (see attached image) is displayed on the screen. There is no explanation of what is happening, so it is unclear (especially if you have no influence) what to do. I thought it was an error at first.

It would be helpful to have a line like "Gain one resource per influence". It would also be helpful for the dialog to NOT appear if you have no influence.

Thank you.

**Comment by vincentneko** [comment]
Just checked the code, the part where you select resources is triggered only if 
`turmoil.getPlayerInfluence(player) > 0`

Are you sure the dialog window appeared and you had to select 0 resources ?

Btw there I don't see the attached image.

I will update the title to something like :
Gain x resource(s) for influence

**Comment by vincentneko** [comment]
What is misleading here also is that your influence when the event is resolved is not matching the board situation because the new government has already been set.

I've also spotted another bug : 
The interrupts related to global events are resolved during first turn, they should be resolved before.

**Comment by vincentneko** [comment]
Merged
