### ISSUE TITLE
Game  error

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#707]
![image](https://user-images.githubusercontent.com/16096558/82207111-e443f300-993b-11ea-8be1-d12cd5151dc5.png)
when I play with my friend , the  page   suddenly  show a dialog,  and  we canot cotinue playing. 
why it happened  , and  what can  we  do ?
the game url : 
https://terraforming-mars.herokuapp.com/player?id=3daab0f648bf

**Comment by bafolts** [comment]
The game hosted on heroku was always intended for demo purposes but more and more players seem to be using it for their own games. You should try hosting the game locally. Errors on the demo server are hard to track down as the demo server was never designed to be able to debug errors. Yesterday around 3:00AM MST there was a deploy which is roughly when this issue was filed. We attempted to put in code which would address these issues but it must not have worked. Running the game locally is easy enough and this is how the game was designed to run.

**Comment by bafolts** [comment]
We most likely need to configure the cache dir to include our database file.

https://devcenter.heroku.com/articles/nodejs-support#custom-caching

**Comment by jijiqw** [comment]
tks a lot , we will try running the game locally
