### ISSUE TITLE
Improvement: Show discounts on card price

### ISSUE THREAD

**Issue by funkybaboon** [bafolts/terraforming-mars#776]
If I get any discount on a card price, It is not reflected in the price tag.

Suggestion: Add the discounted price to the price tag. Show the original price strike through, f.ex. like this:

<img width="659" alt="Screenshot 2020-06-06 at 12 58 56" src="https://user-images.githubusercontent.com/2966599/83942641-c3154a80-a7f5-11ea-9876-1f310c3f9814.png">

This was done with the chrome developer Tools changing the price div to

```
<div class="price ">
  <del>27</del>
  " 25"
</div>
```

and changing the width from 44px to 100px.

**Comment by nwai90** [comment]
Related to https://github.com/bafolts/terraforming-mars/issues/412 as all displayed cost values are currently hardcoded in HTML_data

**Comment by FrankJones314** [comment]
A related idea - someone suggested this one steam for the asmodee version:  Maybe an indicator of which cards are not yet playable or no loner playable because of global parameters.   As it stands now, when clicking "[p;lay a card" it hides ones that we cannot afford And that have global parameter issues.    That sometimes results in misplays of thinking, "ell, after I place the greenery next to three oceans I'll have the 6 MC for this card" except then realizing the oxygen is too high.  

It would be similar  to the showing the true cost and adjusted cost after discounts.   Maybe the global parameter requirement area of the card could turn green when it has been reached (including adjustments for adaptation tech and special design), and can turn permanent red once a parameter has been passed.  

Perhaps tag requirements can be done similarly.   When someone plays his 5th science tag, for example, something near the "requires 5 science tags" text on mass converter changes to green or something.

**Comment by kevinb9n** [comment]
@FrankJones314 I just happened to file the same request, as part of bug 1407.

**Comment by kevinb9n** [comment]
It may be hard to include both pieces of information (printed cost and effective cost) without it looking bad, so another option might be a toggle button somewhere (preferably not hidden away in settings?) between seeing cards-as-printed and cards-as-modified-by-effects. I think this should include cost mods and requirement mods. We should have a convention that the info is styled slightly differently (e.g. cost in dark green characters instead of black?) whenever it's modded. And maybe hovering on the cost or requirement should show the opposite mode......

**Comment by kevinb9n** [comment]
I filed #2187 to discuss the generalized approach toward viewing cards as modified by effects. That issue perhaps subsumes this one now, except that that issue isn't meant to be solved all at once, so we may want to keep this one so it can be marked closed if just the cost part of it happens.

**Comment by nwai90** [comment]
Closing as discount is implemented
