### ISSUE TITLE
Suggestion: Clearly indicate end of game to players

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#777]
Some ideas:
- Show a temporary message (e.g. "Mars is terraformed!") to players
- Style all global parameter values to a different colour when Mars is terraformed

**Comment by FrankJones314** [comment]
For solo mode this would also be helpful (similar to the steam version; one of the few things they did correctly).  I had two games that I "lost" (I counted them as wins) because I had literally 175 MC and spent them all on cities and greeneries not realizing I needed one more temperature bump.  

Having the portion of the corresponding semicircle around the board for each of the three parameters completely change color when it is completed might be an idea also.

**Comment by nwai90** [comment]
Handled in https://github.com/bafolts/terraforming-mars/pull/893. Possibly improve alert UI / use animation in future
