### ISSUE TITLE
Improve log with icons

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#884]
The game log could use icons for resources instead of text.
Example : John Doe spent 1 plants to gain 7 MC => John Doe spent 1 &#x1F331; &#xFE0E; to gain 7 MC

This will avoid handling singular or plural depending the number of resources.

**Comment by ssimeonoff** [comment]
The risk is that the unicode chars are rendered differently on different OSs (or completely skipped). 
The reason is that the text variation selector FE0E does not work for all glyphs for OSs different from Windows.
For example, the unicode chars I was using for the tags looked like this: 
https://boardgamegeek.com/image/4040854/viximo
On Windows 7 and 10, the unicode glyphs are displayed -  FE0E works and prevents the browsers to render them as emojis.
On the other OSs, it is a complete mess.

**Comment by vincentneko** [comment]
I was using unicode character for demonstration. I think we should use images here so we are consistent across browsers / fonts.

**Comment by kberg** [comment]
Images make the app less accessible, unfortunately.

**Comment by kevinb9n** [comment]
See https://github.com/bafolts/terraforming-mars/issues/1976#issuecomment-735483731
