### ISSUE TITLE
Pristar can work incorrectly

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#888]
I will try to reproduce it, but Pristar's ability stops to work under some conditions...

**Comment by jijiqw** [comment]
It happens when the  Reds becomes ruling party

**Comment by jijiqw** [comment]
It doesn't happen every time    the Reds becomes ruling party ,  but every time that happens ,   the Reds seems becomes ruling party

**Comment by jijiqw** [comment]
I found why , the pristar 's prop lastGenerationTR reset to 0 when game  object   rebuild from database , it happens when  players undo action or  game server restart .  this problem should solved by   pull request   [https://github.com/bafolts/terraforming-mars/pull/913](url)  https://github.com/bafolts/terraforming-mars/pull/913#issue-444298260

**Comment by jijiqw** [comment]
There may be other corps have  similar bugs

**Comment by alrusdi** [comment]
Great. Let's merge it

**Comment by nwai90** [comment]
@alrusdi Can we close this one?

**Comment by alrusdi** [comment]
I think so
